pfsense/pfsense-packages

config/ntopng/ntopng.xml, pkg_config.10.xml, pkg_config.8.xml, pkg_config.8.xml.amd64
add checkbox to enable historical data storage
ntopng Command Line Options:
--dump-flows | -F
Dump expired flows. If ntopng is compiled with sqlite support, flows can dumped persistently on disk using this option. Databases are created daily under /db.
https://forum.pfsense.org/index.php?topic=80461.msg473467#msg473467
=> ntopng - add checkbox to enable historical data storage

config/snort/snort.inc, config/snort/snort.xml, pkg_config.10.xml, pkg_config.8.xml, pkg_config.8.xml.amd64
Forum report: https://forum.pfsense.org/index.php?topic=86562.0
@bmeeks8 - this just looked wrong, because the end of snort_create_rc() has:
/* write out snort.sh */
@file_put_contents("{$rcdir}snort.sh", $snort_sh_text);
@chmod("{$rcdir}snort.sh", 0755);
which seems to clearly create snort.sh
I do not run snort, so I haven't tested this! Feel free to ignore my pull request, and include this fix in the next set of snort bug fixes and version bump.
=> Remove the correct snort.sh on deinstall

config/squid3/34/squid.inc, config/squid3/34/squid.xml, config/squid3/34/squid_antivirus.xml, config/squid3/34/squid_clwarn.php, pkg_config.10.xml
/var/run/squid check
squidclamav symbolic links
antivirus tab check config
c-icap rc.d file path checks
clamd rc.d file path checks
squid_clwarn.php replacement for clwarn.cgi to do not need perl install
=> squid 3.4 - fixes #4196 and #4197

config/openvpn-client-export/vpn_openvpn_export.php
The $server array here has and "index" key, not an "sindex" key.
Actually nothing was broken by this. When the user switches server selections, server_changed() is called. That uses JavaScript and selectedIndex to work out which entry the user selected. selectedIndex is a zero-based number. It matches the zero-based index of servers, which was built from the zero-based indexes of $ras_server array, which was built from data in the config. So by good luck or good management, this array index name typo is not actually a bug.
I noticed it while investigating forum https://forum.pfsense.org/index.php?topic=86263.0
=> OpenVPN export fix index typo

config/suricata/suricata_global.php
Suricata 2.0.4 pkg v2.1.3
===================
This update for Suricata simply corrects two typos where "Snort" is used instead of "Suricata" in some descriptive text on the GLOBAL SETTINGS tab.  There are no changes to functionality and a package version bump is not required.
Bug Fixes:
--------------
1. Change "Snort" to "Suricata" in text for ET-Open and ET-Pro rule descriptions on GLOBAL SETTINGS tab.
=> Suricata Package:  Fix typos where "Snort" should be "Suricata" in labels.

config/pfblockerng/pfblockerng.inc, pkg_config.10.xml
Some IBlock lists have an issue with the existing Range to CIDR function. The Stilez Range to CIDR function does not exhibit this behavior. Once the existing Range to CIDR function is fixed/or replaced with the Stilez function, this PR can be reverted.
=> pfBlockerNG v1.0 - Temporary fix for Range to CIDR Issue

pkg_config.10.xml
Suricata 2.0.6
------------------
This updates the PBI build options for the Suricata package to match up with the latest OPTIONS knobs from FreeBSD Ports.  This update is currently only for pfSense 2.2 and higher.
Please build new Suricata 2.0.6 PBI packages for pfSense 2.2 after merging this update.
=> Suricata - Update build options for 2.0.6 PBI pkg.

config/havp/antivirus.php, config/havp/havp.inc, config/havp/havp.xml, config/havp/havp_avset.xml, config/havp/havp_log.php, pkg_config.10.xml, pkg_config.8.xml, pkg_config.8.xml.amd64
HAVP webConfigurator "Log" checkbox not using at all. Error logs was written always, regardless of "Log" option. Change this behaviour to reflect configurator option. Note: HAVP access log writes always because of virus attentions.
=> HAVP configurator "Log" option now really using

pkg_config.10.xml
Suricata 2.0.6 pkg v2.1.3
---------------------------------
This updates the binary version of the Suricata PBI package to 2.0.6 and brings the pfPorts version to the same level as the FreeBSD port.  Information on the upstream bug fixes in this release can be found at http://suricata-ids.org/2015/01/15/suricata-2-0-6-available/.
=> Update Suricata PBI to version 2.0.6

config/squid3/34/squid.inc, config/squid3/34/squid.xml, pkg_config.10.xml
removed 'disable_xforward' field and replaced it with 'xforward_mode' since this a re-write of the GUI option
adding 5 forward_for options per
http://www.squid-cache.org/Versions/v3/3.4/cfgman/forwarded_for.html
https://forum.pfsense.org/index.php?topic=85280.msg476632#msg476632
=> Add new X-Forward Mode option to GUI

pkg_config.10.xml, pkg_config.8.xml, pkg_config.8.xml.amd64
Preparing for upgrade.
Need to build all binaries: zabbix2 agent and proxy
=> zabbix2 - update packages to 2.4.2 - first step

config/haproxy-devel/haproxy.inc, config/haproxy-devel/haproxy.xml, config/haproxy-devel/haproxy_listeners.php, config/haproxy-devel/haproxy_listeners_edit.php, config/haproxy-devel/haproxy_pool_edit.php, config/haproxy-devel/haproxy_utils.inc, config/haproxy-devel/pkg/haproxy_upgrade_config.inc, config/haproxy-devel/www/javascript/haproxy_geturl.js, pkg_config.10.xml, pkg_config.8.xml, pkg_config.8.xml.amd64
haproxy-devel, several improvements / fixes
-combine certificate acl's with user acl's
-wildcard certificate acl handling
-better handeling of 'transparent' backends when using mixed ipv4 and ipv6, a single defined backend can write 2 backends to the config ipv4 / ipv6
-option to negate a acl
-moved acl definitions above advanced user config in cfg (to allow user config to use already defined acls)
-toggle in frontend overview to easily enable/disable a frontend
=> haproxy-devel, several improvements / fixes

config/haproxy-devel/haproxy.inc, config/haproxy-devel/haproxy.xml, config/haproxy-devel/haproxy_global.php, config/haproxy-devel/haproxy_listeners.php, config/haproxy-devel/haproxy_listeners_edit.php, config/haproxy-devel/pkg/haproxy_upgrade_config.inc, pkg_config.10.xml, pkg_config.8.xml, pkg_config.8.xml.amd64
haproxy-devel, 0.17, acl's are merged when duplicates exist, better client certificate handling, checkbox options for allowing no/invalid client certs instead of the 'none'-ca which wasn't 'user friendly'.
=> haproxy-devel, 0.17, better client certificate handling, acl merging

config/haproxy-devel/haproxy.inc, pkg_config.10.xml, pkg_config.8.xml, pkg_config.8.xml.amd64
haproxy-devel, 0.18, make sure frontend without acl's is last 'default' even when system acl is added
=> haproxy-devel, 0.18, make sure frontend without acl's is last 'default' even when system acl is added

config/suricata/suricata.inc, config/suricata/suricata.xml, config/suricata/suricata_alerts.php, config/suricata/suricata_barnyard.php, config/suricata/suricata_blocked.php, config/suricata/suricata_define_vars.php, config/suricata/suricata_interfaces_edit.php, config/suricata/suricata_ip_list_mgmt.php, config/suricata/suricata_ip_reputation.php, config/suricata/suricata_passlist.php, config/suricata/suricata_passlist_edit.php, config/suricata/suricata_post_install.php, config/suricata/suricata_rules.php, config/suricata/suricata_rulesets.php, config/suricata/suricata_suppress_edit.php, pkg_config.10.xml, pkg_config.8.xml, pkg_config.8.xml.amd64
Suricata 2.0.6 pkg v2.1.4
===================
This update for the Suricata package fixes three user-reported bugs.
Bug Fixes
-------------
1. On the INTERFACE SETTINGS tab, when EVE JSON output to syslog is enabled, then 'send alerts to system log' must also be auto-enabled in order for syslog output to be properly initialized.
2. Multiple cron task entries are generated when editing "rules update" and "remove blocked hosts" intervals.
3. In rare instances, a blank network and subnet string returned for an interface results in an invalid slash "/" character in a PASS LIST.
=> Suricata 2.0.6 pkg v2.1.4 - GUI Package Bug Fix Update

config/zabbix-lts/zabbix-agent-lts.xml, config/zabbix-lts/zabbix-lts.inc, config/zabbix-lts/zabbix-proxy-lts.xml, pkg_config.10.xml
The ideia is keep the packages as they were before and create new ones "Zabbix Agent LTS" and "Zabbix Proxy LTS" with another path of config files.
Proposed:
- Rename packages back.
- Alter package description informing the difference between standard releases and LTS releases.
- Create structure for new packages (LTS) and take out lines of code for keeping compatibility with earlier pfSense versions.
=> Zabbix - New Packages

config/vhosts/vhosts.inc
"bin-path" should be "/usr/local/bin/php"
(same as 7232161e99d60256c1a4ee94ef800f6d4f39764 )
=> vhost: Corrected PHP bin-path for  SSL configuration

config/vhosts/vhosts.inc
Added code to check if the process is running for any vhost lighthttpd configuration.
In this way it's possible to show the service status on each vhost.
=> vhost: Added ['custom_php_service_status_command']

config/snort/snort_alerts.widget.php
Currently if you open the snort widget settings and just press "save" with a blank field, it sets the parameter to blank. Subsequently that causes problems trying to fetch the last "" number of alerts, and actually the little "tool" icon never reappears, so you cannot fix it from the dashboard.
1) Setting the number of entries to 0 seems silly, so limit it to a minimum of 1 alert.
2) If the user blanks the box, then unset widget_snort_display_lines to make sure things will always revert to the default.
3) Whatever else the user types in - "abc", "-999", "23xyz99" - try to interpret it as an int (with intval()), then do not let it be less than 1 (not negative or zero).
This forum entry made me touch it and "break" my widget also: https://forum.pfsense.org/index.php?topic=89161.0
=> Validate widget_snort_display_lines

config/haproxy-devel/pkg/haproxy.inc, config/haproxy1_5/pkg/haproxy.inc, pkg_config.10.xml, pkg_config.8.xml, pkg_config.8.xml.amd64
haproxy-1_5, haproxy-devel, pkg v0.22 fix SNI handling inspect-delay 5s instead if 5ms, show 'not' in acls when set
=> haproxy-1_5, haproxy-devel, pkg v0.22 fix SNI handling inspect-delay 5s instead if 5ms, show 'not' in acls when set

config/snort/snort.xml, config/snort/snort_defs.inc, config/snort/snort_generate_conf.php, config/snort/snort_migrate_config.php, config/snort/snort_post_install.php, config/snort/snort_rulesets.php, pkg_config.10.xml, pkg_config.8.xml, pkg_config.8.xml.amd64
Snort 2.9.7.2 pkg v3.2.4 -- Update
==========================
This updates the Snort package to binary version 2.9.7.2 and the GUI package to version 3.2.4.  Release notes for Snort 2.9.7.2 can be found here: http://blog.snort.org/2015/03/snort-2972-has-been-released.html.  There are three minor bug fixes in the v3.2.4 GUI package update.
Bug Fixes
-------------
1. If you're on the CATEGORIES tab and have enabled "GPLv2 Community Rules (VRT certified)", the hyperlink assigned to it to take you to the ruleset is incorrect.
2. Redmine bug #4912 -- Typo in snort_rulesets.php.  Effect: Number of snort SO (shared object) rules always incorrectly counts as 1. There will be cases where not all snort SO rules are displayed, as $i is set by the other two rulesets.
3. Trailing backslash on …
=> Snort 2.9.7.2 pkg v3.2.4

config/apcupsd/apcupsd.inc, config/apcupsd/apcupsd.xml, config/apcupsd/apcupsd_status.php, pkg_config.10.xml, pkg_config.8.xml, pkg_config.8.xml.amd64
There are some issues with APCupsd status page by misunderstandings.
- add an option for chose host parameter on apcaccess command.
This options is enabled only on pfSense >= 2.2 (APCupsd 3.4.12)
- add a verification if NIS server is running (apcaccess needs to connect on a NIS server, localhost or remote).
- bump version
=> apcupsd - improve status page

config/haproxy-devel/pkg/haproxy.inc, config/haproxy1_5/pkg/haproxy.inc, pkg_config.10.xml, pkg_config.8.xml, pkg_config.8.xml.amd64
haproxy 1.5, bump version on 2.2 to 1.5.11, move advanced frontend settings below forwardfor to avoid a (possible) warning
=> haproxy 1.5, bump version on 2.2 to 1.5.11, move advanced frontend settings below forwardfor

config/bind/bind.inc, config/bind/bind.widget.php, config/bind/bind.xml, config/bind/bind_acls.xml, config/bind/bind_sync.xml, config/bind/bind_views.xml, config/bind/bind_zones.xml
Code cleanup to reflect coding style guidelines and consistency
Tabs only, always uses braces, spacing
C/C++ style comments
Use array_key_exists instead of key_exists
$config[] keys are always enclosed in quotes and use single quotes for literals
=> BIND package code clean up

config/squid3/34/squid.inc
configured port needs checking against sysctl parameter "net.inet.ip.portrange.reservedhigh" instead of "net.inet.ip.portrange.first".
=> correction of portrange checking

config/bind/bind.inc
Initialize variables before .= concatenation
Remove dead code (unused copy/paste of zone CONFIG settings not used in zone DB)
Remove unused [$i] on $custom_root_zone and initialize
=> BIND package code clean up - variable initialization and dead code

config/phpservice/phpservice.xml
This fixes the Status/Services display of the phpservice package.
This should apply to 2.1.5 as well.
=> Fixed phpservice status not being able to extract status from ps.

config/apcupsd/apcupsd.inc, config/apcupsd/apcupsd.xml, pkg_config.10.xml, pkg_config.8.xml, pkg_config.8.xml.amd64
Add another way to send email notifications.
The user can choose between phpMailer or a simple SMTP mail client packaged with APCUpsd.
Bump version.
=> apcupsd - add another way to send email notifications

config/freeradius2/freeradiusclients.xml
Shared secrets longer than 31 characters will display garbage passwords.
Another cause of garbage passwords being logged is the secret being too long. Certain NAS boxes have limitations on the length of the secret and don't complain about it. FreeRADIUS is limited to 31 characters for the shared secret.
http://wiki.freeradius.org/guide/faq#Common-problems-and-their-solutions
=> freeradius2: Show max shared secret length

config/squidGuard/squidguard_configurator.inc
mountpoint for ramdisk needs to be created first, now used PHP mkdir().
umount and mdconfig need complete path.
=> squidguard: repair ramdisk functionality for blacklist updates

config/bind/bind.inc, pkg_config.10.xml, pkg_config.8.xml, pkg_config.8.xml.amd64
The rate-limit option should not have values with {} and look like this:
rate-limit {
responses-per-second 15;
log-only yes;
};
=> BIND - fix rate-limit option - remove {}

config/dansguardian/dansguardian.inc
proxyport setting defaults to localhost IP address rather than default squid proxy port
=> Fix invalid proxyport default

config/suricata/suricata.xml, config/suricata/suricata_check_cron_misc.inc, config/suricata/suricata_logs_mgmt.php, config/suricata/suricata_migrate_config.php, config/suricata/suricata_post_install.php, pkg_config.10.xml
Suricata 2.1.5 Update
-----------------------------
This updates the underlying Suricata PBI binary package to v2.0.8_1.  The GUI package is updated to v2.1.5.
New Features
------------------
1. Support for PPPoE connections was back ported from the 2.1-BETA upstream code base.
2. A new retention setting for captured TLS Certs on the LOGS MGMT tab.
Bug Fixes
-------------
1. Log retention settings for the LOGS MGMT tab are global data but were being duplicated for each configured Suricata interface.
=> Suricata 2.1.5 Update

config/pfblockerng/pfblockerng.inc, config/pfblockerng/pfblockerng.php, config/pfblockerng/pfblockerng.priv.inc, config/pfblockerng/pfblockerng.sh, config/pfblockerng/pfblockerng.widget.php, config/pfblockerng/pfblockerng.xml, config/pfblockerng/pfblockerng_alerts.php, config/pfblockerng/pfblockerng_diag_dns.php, config/pfblockerng/pfblockerng_log.php, config/pfblockerng/pfblockerng_sync.xml, config/pfblockerng/pfblockerng_top20.xml, config/pfblockerng/pfblockerng_update.php, config/pfblockerng/pfblockerng_v4lists.xml, config/pfblockerng/pfblockerng_v6lists.xml, pkg_config.10.xml
- Code Style improvements
- Add option to customize the Inbound Ports and Destination Addresses using pfSense Aliases.
- Add function to check if Cron task needs updating. Minimize Config backups.
- Cron time function moved from .php to .inc file
- Cron settings now allow for hour 'interval' customizations.
- Added preliminary code "$pfb['cron_mod']" which will only save the config when changes are found. This will avoid creating config backups when not required. Not fully implemented.
- Remove code to determine pfSense version below 2.2
- Remove code to check for presence of pfBlocker original version.
- Reduce blank lines in pfblockerng.log
- Adjust IP regex for CIDR matching
- Remove '/32' from Lists as pf strips this out anyways
- When parsing IP lists, use regex to find Ranges first …
=> pfBlockerNG v1.09 05-2015-1

pkg_config.10.xml
haproxy-devel, include lua53 for compilation of haproxy 1.6-dev1
@rbgarga , please also check openssl version that gets compiled into the pbi today seems to be confused what version it uses when running "haproxy -vv" after installing the pbi it outputs:
Built with OpenSSL version : OpenSSL 1.0.2a 19 Mar 2015
Running on OpenSSL version : OpenSSL 1.0.1m 19 Mar 2015 (VERSIONS DIFFER!)
Should any additional build options be set? Or is it a problem with the buildserver/scripts perhaps?
=> haproxy-devel, include lua53 for compilation of haproxy 1.6-dev1

config/backup/backup.inc, pkg_config.10.xml, pkg_config.8.xml, pkg_config.8.xml.amd64
As reported in forum https://forum.pfsense.org/index.php?topic=95790.0
When Backup and Vhosts package are both installed there can be errors
logged about Cannot redeclare byte_convert().
=> Backup pkg check if byte_convert function exists

config/mailreport/status_mail_report_add_cmd.php
Existing code was referencing the wrong variable (`$a_graphs` instead of `$a_cmds`), which caused the `if` test to fail, which then caused duplicate entries to be created each time the Edit function of the "Report Commands" form was submitted.  This patch fixes the issue. Tested on pfSense 2.1.5 nanobsd.
=> Fix bug in status_mail_report_add_cmd.php

config/apache_mod_security-dev/apache_mod_security.inc, pkg_config.10.xml
Leaving the Backend Path blank does not add / to backendpath in configuration, contrary to what's suggested in the GUI, resulting in HTTP 503 Error.
=> apache_mod_security-dev - fix Bug #3360, Bug #4421

config/freeradius2/freeradius.inc, config/freeradius2/freeradius_view_config.php, config/freeradius2/freeradiusauthorizedmacs.xml, config/freeradius2/freeradiuscerts.xml, config/freeradius2/freeradiusclients.xml, config/freeradius2/freeradiuseapconf.xml, config/freeradius2/freeradiusinterfaces.xml, config/freeradius2/freeradiussync.xml, pkg_config.10.xml, pkg_config.8.xml, pkg_config.8.xml.amd64
Replaces pull  #831
Removed and from files other than freeradius.xml, since that is the main package config file where these things need to be defined.
Kill radiusd processes during deinstall. RC script fails to stop radiusd process because it calls script from freeradius package and that package is uninstalled before RC script is called. #4346
=> General freeradius2 cleanup and fix for #4346

config/stunnel/stunnel.inc, config/stunnel/stunnel.xml, pkg_config.10.xml
This fixes stunnel start/stop from the GUI by correcting the rcfile in stunnel.xml and adds the ability to create client mode tunnels from the GUI.
Tested with a local package repository and it appears to work properly.
The package still fails to start if the "cert = ..." line is present, which I think is due to an outdated package.  Installing stunnel 5.19 with "pkg install stunnel" fixes that issue, so I think the pbi needs to be updated as well, but I don't have access to the pfsense-tools repo to hack on that.
=> Minor Stunnel Improvements

config/systempatches/system_patches.php
For ease of use:
1) Add a single "Status" column
2) Merge "Apply" and "Revert" into a single column (they are mutually exclusive reverses of each other so it flows better)
3) Fix logic at old lines 225-228: at present if location and patch both blank, it will offer "fetch", but it can't fetch a patch if a location isn't held, so this is incorrect. Need to check empty(location) *first* and then, *if* a location is held, use empty(patch) to decide whether the GUI text is "fetch" or "refetch". (Fixed code is @ lines 241-242)
=> System patches: Add status column and other GUI improvement

config/ntopng/ntopng.xml
Need to run gzip -d with --force switch, otherwise the files don't get decompressed on update:
```
php-fpm[90509]: /pkg_mgr_install.php: The command '/usr/bin/gzip -d '/usr/pbi/ntopng-amd64/share/ntopng/GeoLiteCityv6.dat.gz'' returned exit code '1', the output was 'gzip: /usr/pbi/ntopng-amd64/share/ntopng/GeoLiteCityv6.dat already exists -- skipping'
```
=> ntopng - Some more fixes for this package

config/ntopng/ntopng.xml, pkg_config.10.xml
The target directory does not exist on reinstall. Need to create it to avoid these errors:
```
Starting package ntopng...
Warning: symlink(): No such file or directory in /etc/inc/pkg-utils.inc(423) : eval()'d code on line 159
Warning: symlink(): No such file or directory in /etc/inc/pkg-utils.inc(423) : eval()'d code on line 159
Warning: symlink(): No such file or directory in /etc/inc/pkg-utils.inc(423) : eval()'d code on line 159
Warning: symlink(): No such file or directory in /etc/inc/pkg-utils.inc(423) : eval()'d code on line 159
```
=> ntopng - need to create $target_dir before symlinking

config/mtr-nox11/mtr-nox11.xml, pkg_config.10.xml
1. Change the report format to wide to avoid cut off hostnames.
2. Added multiple options:
* --no-dns (skip DNS lookups)
* --show-ips (display both the host names and numeric IP numbers)
* --raw (raw output format)
* --interval (specify interval between ICMP reqs)
* -4 (use IPv4 only)
3. Command options are shown before the output
4. Added a Back button after command output, to go back to mtr menu
1. Add basic input validation
* check valid hostname/IP, also mark the field as required
* on invalid count input, default to 10, otherwise, convert the input to integer
* Added a Back button after failed input validation
Fix indentation, fix package name in header, fix copyright, etc.
=> mtr-nox11 - multiple improvements plus code style fixes

config/ftpproxy/ftpproxy.inc, config/ftpproxy/ftpproxy.xml, pkg_config.10.xml
- Also removed chmod 077 for the inc file, really don't get the point here?! (Seems like it's being pasted from the test_package into quite a few other packages.)
- Removed accidental double space in one of the descriptions.
=> FTP Client Proxy - add standard XML and copyright headers

config/syslog-ng/syslog-ng.inc, pkg_config.10.xml
Fix the path to logrotate binary + clean up after itself on uninstall.
=> Bug #4612 - fix syslog-ng logrotate cron job

config/ntopng/ntopng.xml, pkg_config.10.xml
Symlink the scripts directory to /usr/local/share/ntopng to reduce logspam caused by PBI stupidity. (Declare $pf_version global on first use while at it, and clean up after itself on uninstall.)
=> ntopng - attempt to reduce log spam (resubmit of #915)

config/blinkled/blinkled.inc, config/blinkled/blinkled.xml, pkg_config.10.xml
(Resubmit of #921.)
- Improve service description.
- Remove blinkled_stop() and blinkled_running() functions, used just once -> pointless.
- Use is_process_running()
=> blinkled - code style fixes, add copyright headers

config/nut/nut.inc, config/nut/nut.xml, config/nut/status_nut.php, pkg_config.10.xml
nut.xml and status_nut.php contain just code style fixes per developer style guide.
nut.inc was a **lot** of work
1. nut_notice() and nut_warn() functions removed; use log_error() instead
2. nut_action() function removed; use service_start() and service_stop() instead
3. nut_validate_ip() function removed (WTF); use is_ipaddr() instead
4. replace deprecated eregi() with preg_match()
5. *major* coding style cleanup
6. use full paths to commands in the heredocs
=> nut - major code cleanup, code style fixes

config/softflowd/softflowd.xml, pkg_config.10.xml
- Do not try to restart service on boot, otherwise it may get started twice via /etc/rc.start_packages (Fixes bug #4731).
- Add standard XML and copyright headers.
- Remove doubled spaces between sentences in descriptions.
- Developer style guidelines (spacing, braces).
=> softflowd - do not restart on boot plus style fixes

config/nrpe2/nrpe2.inc, config/nrpe2/nrpe2.xml, pkg_config.10.xml
nrpe2.xml
- Add copyright header (from git history)
- Nuke useless tags and fix file permissions.
- Descriptions cosmetics.
nrpe2.inc
- Code style
- FIx NRPE_BASE for pfSense 2.3
- Use restart_service() and stop_service() instead of calling the shell script directly
=> nrpe2 - code style fixes

config/pfflowd/pfflowd.xml
Note: I am NOT bumping the version here, since this is only usable as a disk benchmark ATM. Once Bug #4304 is fixed, it can get a version bump.
P.S. Copyright info taken from git commits history.
=> pfflowd - code style fixes, add copyright header

pkg_config.10.xml
While here, I also
- nuked some empty tags
- changed the indentation of <descr> tags which use CDATA to make those easily readable and editable, nuked bunch of pointless CDATA
- added/updated a couple of website links, removed links to some dead websites
- added a forum link for the FTP proxy package
=> Improve package descriptions, fix website links, cleanup

config/tftp2/tftp.inc, config/tftp2/tftp.xml, config/tftp2/tftp_files.php, pkg_config.10.xml
tftp.xml:
- fix copyright header
- fix file permissions
- indentation
tftp.inc:
- Remove unused functions
- Use safe_mkdir() 
- Improve the backup restore code
- Indentation and code style fixes
tftp_files.php
- fix copyright header
- fix code indentation
- XHTML valid code
- make it possible to actually unset the selected TFTPD interfaces
=> tftp - major package code cleanup

config/arpwatch/arpwatch.xml, config/arpwatch/arpwatch_reports.php, config/arpwatch/sm.php, pkg_config.10.xml
arpwatch.xml
- Fix chmod
- Remove obsolete pfSense version check
- Code style cleanup
- Remove useless config_(un)lock calls
- Add custom_php_resync_config_command
sm.php
- Add missing copyright header
- Remove obsolete pfSense version check
- Code style cleanup
arpwatch_reports.php
- Fix nanobsd
- Code style
- Fix XHTML
=> arpwatch - code style cleanup

config/snort/snort.xml, config/snort/snort_sync.xml
Get rid of loads of bad 077 chmods, also no need to chmod 0644 which is default.
Nuke useless, unused XML tags
Fix title and make version consistent.
Done here; not touching anything else here since it's very actively maintained.
@bmeeks8 Hope you don't mind this very small cleanup. ;)
=> snort - fix copyright headers, XML cleanup

config/haproxy-devel/haproxy.xml, pkg_config.10.xml
Updated copyright header and nuked useless unused tags while here.
I bumped the package version. Thinking about this, these broken permissions have potential security impact.
=> haproxy-devel - fix file permissions

config/quagga_ospfd/quagga_ospfd.xml, config/quagga_ospfd/quagga_ospfd_interfaces.xml, config/quagga_ospfd/quagga_ospfd_raw.xml, pkg_config.10.xml
0644 is default -> pointless. The shell script does not need to be world-writeable. 
Added copyright header, and improved descriptions readability while here.
=> quagga_ospfd - fix file permissions

config/suricata/suricata.xml
None of these files need to be executable and 0644 is default -> pointless. Fix copyright header and nuke useless empty tags while here.
=> suricata - fix file permissions

config/autoconfigbackup/autoconfigbackup.inc, config/bandwidthd/bandwidthd.inc, config/darkstat/darkstat.xml, config/ftpproxy/ftpproxy.inc, config/haproxy-legacy/haproxy_frontends.php, config/haproxy-legacy/haproxy_servers.php, config/haproxy/haproxy_listeners.php, config/haproxy/haproxy_pools.php, config/imspector/imspector.inc, config/ntop2/ntop.xml, config/ntopng/ntopng.xml, config/nut/nut.inc, config/pfflowd/pfflowd.xml, config/softflowd/softflowd.xml, config/spamd/spamd_db_ext.php, config/spamd/spamd_verify_to_address.php, config/squid/squid_auth.inc, config/squid/squid_ng.inc, config/squid3/31/squid_auth.inc, config/squid3/31/squid_ng.inc, config/squid3/33/squid_auth.inc, config/squid3/33/squid_ng.inc, config/strikeback/strikeback.inc, config/stunnel/stunnel.inc, config/tinydns/tinydns.inc, config/widentd/widentd.xml
This function does nothing but return. (No version bumps here, would be a waste of time to make people reinstall because of this.)
=> remove useless config_(un)lock calls

pkg_config.8.xml
This package is completely broken, calling pkg_add/pkg_delete, generally WTF code.
=> Disable strikeback package on 2.2

config/lcdproc-dev/lcdproc.inc, config/lcdproc-dev/lcdproc.xml, config/lcdproc-dev/lcdproc_screens.xml, pkg_config.10.xml
Get fix from #945  into the -dev version as well. (Planning to do a code style cleanup for this one as well, but it takes some time.) Also, remove useless config_(un)lock calls while here.
=> lcdproc-dev localhost fix, remove useless config_(un)lock calls

config/bandwidthd/bandwidthd.inc, config/bandwidthd/bandwidthd.xml, pkg_config.10.xml
bandwidthd.xml
- Fix copyright header and indentation
- Reorder the GUI and split into logical sections
- Improve descriptions
- Move the menu entry to Diagnostics section, to match other similar packages (ntop, ntopng, darkstat etc.)
- Add another menu entry to access bandwidthd graphs directly from menu
- Add input validation
bandwidthd.inc
- Update copyright headers
- Fix code style and indentation
- Provide input validation for most of the configuration options
-- Check for IPv4 configured on selected interfaces
-- Check for PPPoE type interfaces
-- Require relevant options to be filled in when PostgreSQL is enabled (also check that the hostname is valid)
-- Require sane numeric input for graphs options
-- Limit Sensor ID to sane chars
- PostgreSQL DB password is now base64-encoded to …
=> bandwidthd - code style and major improvements

config/bacula-client/bacula-client.inc, config/bacula-client/bacula-client.xml, config/bacula-client/bacula-client_fd.xml, config/bacula-client/bacula-client_view_config.php, pkg_config.10.xml
bacula-client.xml, bacula-client_fd.xml
- Fix copyright header and indentation
- Remove unused tags
- Sanitize version
- Improve some descriptions
bacula-client.inc
- Fix copyright header and indentation
- Fix pfSense version checks
- Remove unused global vars declaration
- Use stop_service() and restart_service()
- Make sure that at least one local Director is configured before trying to start the service, otherwise it fails (see e.g. https://forum.pfsense.org/index.php?topic=97934.0)
bacula-client_view_config.php
- Fix pfSense version checks
- Nuke obsolete pfSense 1.2.x junk
- Code style and indentation
=> bacula-client - code style fixes

config/backup/backup.inc, config/backup/backup.php, config/backup/backup.xml, config/backup/backup_edit.php, pkg_config.10.xml
backup.xml
- Removed self-referencing additional_files_needed 
- Remove pointless/unused tags
- Remove WTF &lt;fields&gt; copy/paste code coming from god knows where
- Removed no-op duplicated &lt;tab&gt; and fix the url in the other one
- Fix files permissions
backup.inc
- Removed unused byte_convert() function
- Rename backup_sync_package_php() to backup_sync_package() and get rid of the original backup_sync_package()  which only called the other one.
backup.php, backup_edit.php
- Clean up obvious leftover crap
- XHTML valid code
=> backup package - cleanup round two

config/syslog-ng/syslog-ng.inc, config/syslog-ng/syslog-ng.xml, config/syslog-ng/syslog-ng_advanced.xml, config/syslog-ng/syslog-ng_log_viewer.php, pkg_config.10.xml
syslog-ng.xml
- Sanitize package version and make it consistent across XML files
syslog-ng_advanced.xml
- Sanitize package version and make it consistent across XML files
syslog-ng.inc
- Update copyright header
- Use get_interface_ip() instead of parsing ifconfig output
- Use {start,stop,restart}_service() instead of exec()
- Use rename() instead of mv.
- Use platform_booting() to check whether system is booting
syslog-ng_log_viewer.php
- Valid XHTML
=> syslog-ng - code style fixes

config/lcdproc/lcdproc_client.php, pkg_config.10.xml
- Fix remaining indentation/whitespace
- Replace deprecated split() with explode()
- Use full paths to commands consistently
=> lcdproc - additional code style fixes

config/sshdcond/sshdcond.inc, pkg_config.10.xml
When you install but never configure this package, on boot you get this warning:
```
Starting package SSHDCond...
Warning: Invalid argument supplied for foreach() in /usr/local/pkg/sshdcond.inc on line 127
done.
```
Problem being that the whole function logic is wrong. Trying to fix here. (Comments included in the code, hopefully the logic is clear and correct now.)
=> sshdcond - fix sshdcond_sync_on_changes() logic

config/apcupsd/apcupsd.conf.php, config/apcupsd/apcupsd.inc, config/apcupsd/apcupsd.xml, config/apcupsd/apcupsd_mail.php, config/apcupsd/apcupsd_status.php, pkg_config.10.xml
apcupsd.xml
- Fix indendation
- Fix file permissions (no need for these to be executable)
- Remove useless empty tags
- Attempt to make the descriptions more readable.
apcupsd.inc
- Fix copyright headers
- Code style cleanup
- Use stop_service()/restart_service()
- Fix pfSense version checks
apcupsd.conf.php
- Fix copyright headers
apcupsd_mail.php
- Update copyright headers
apcupsd_status.php
- Remove outdated pfSense <=2.0 stuff and other junk
- Fix broken pfS version check
- Code style cleanup
- Valid XHTML
@dbaio - You might want to check this as well. ;)
=> apcupsd - code style cleanup

config/snort/snort.inc, config/snort/snort.xml, config/snort/snort_check_for_rule_updates.php, config/snort/snort_defs.inc, config/snort/snort_migrate_config.php, config/snort/snort_passlist.php, config/snort/snort_passlist_edit.php, config/snort/snort_post_install.php, pkg_config.10.xml
Snort 2.9.7.5 pkg v3.2.7
==================
This updates the Snort binary to version 2.9.7.5 and the GUI package to version 3.2.7.  One new feature is introduced and three reported bugs are fixed in this release.
New Features
------------------
1.  The custom blocking Snort output plugin now includes code to monitor all of the firewall interfaces and automatically add the interface IP addresses to an internal Pass List so that firewall interface IPs themselves are never blocked.  This is most helpful for users with a frequently updating dynamic WAN IP address.  The blocking module will now be immediately notified of the updated WAN IP address and will add it to an internal automatic Pass List and remove the old IP from the same list.  This should prevent inadvertent blocking of the WAN IP …
=> Snort 2.9.7.5 pkg v3.2.7

config/zabbix-proxy-lts/zabbix-proxy-lts.inc, config/zabbix-proxy-lts/zabbix-proxy-lts.xml, pkg_config.10.xml
zabbix-proxy-lts.xml
- Fix file permissions
- Nuke unused/useless tags
- Move advanced options to advancedfield
zabbix-proxy-lts.inc
- Code style and allignment fixes
- Remove unused php_install_zabbix_proxy_lts() function
- Use stop_service()/restart_service()
=> zabbix-proxy-lts - code style cleanup

config/zabbix-agent-lts/zabbix-agent-lts.inc, config/zabbix-agent-lts/zabbix-agent-lts.xml, pkg_config.10.xml
zabbix-agent-lts.xml
- Fix file permissions
- Nuke unused/useless tags
- Improve some descriptions.
- Move User Parameters to advancedfield
zabbix-agent-lts.inc
- Code style and allignment fixes
- Remove unused php_install_zabbix_agent_lts() function
- Use stop_service()/restart_service()
- Use mwexec() instead of exec()
- Improve some input validations
=> zabbix-agent-lts - code style cleanup

config/nut/nut.inc, pkg_config.10.xml
NUT takes quite some time to launch (notably with networked UPS); this creates misleading log entries confusing users.
=> Remove useless log spam

config/arpwatch/arpwatch.xml, pkg_config.10.xml
You can end up with orphaned /usr/sbin/sendmail as a copy of sm.php script, causing cron and other unwanted spam even after uninstalling the package. I recall couple of users complaining on the forum, examples: 
https://forum.pfsense.org/index.php/topic,68004.0.html
https://forum.pfsense.org/index.php?topic=74000.msg406041#msg406041
This still is not a proper fix, this shouldn't require and create /usr/sbin/sendmail at all. Debian ships this with a patch adding -s option to specify sendmail path:
```
-s
flag is used to specify the path to the sendmail program.
Any program that takes the option -odi and then text from stdin
can be substituted. This is useful for redirecting reports
to log files instead of mail.
```
=> arpwatch - do not create sendmail hardlinks... Evil.

config/snort/snort.inc, pkg_config.10.xml, pkg_config.8.xml, pkg_config.8.xml.amd64
snort, fix config-sync to 'system backup server'
=> snort, fix config-sync to 'system backup server'

config/ipguard/ipguard.inc, config/ipguard/ipguard.xml, config/ipguard/ipguard_sync.xml, pkg_config.10.xml
ipguard.xml
- Fix copyright header, indentation
- Fix file permissions
- Remove unused tags
- Improve descriptions
ipguard_sync.xml
- Remove unused tag
- Fix version
ipguard.inc
- Hack to make this work on 2.2.x by symlinking the .conf files to PBI's /etc dir; another piece of PBI stupidity.
- Fix bogus boot check
- Clean up after itself a bit better on uninstall.
=> ipguard - make it work on 2.2.x plus code style cleanup

config/havp/antivirus.php, config/havp/havp.inc, config/havp/havp.xml, config/havp/havp_avset.xml, config/havp/havp_fscan.xml, config/havp/havp_log.php, pkg_config.10.xml
havp.xml, havp_avset.xml, havp_fscan.xml
- Add copyright header
- Fix indentation/whitespace
- Improve descriptions
havp.inc
- Update copyright header
- Loads of code style/indentation/whitespace fixes
- Replace deprecated eregi() with preg_match
- Use install_cron_job() instead of re-implementing it
- Nuke bunch of useless pfSense 1.2.x checks
- Fix lots of hardcoded ClamAV mirrors
havp_log.php, antivirus.php
- Update copyright header
- Fix indentation/whitespace
- XHTML fixes
=> havp code style cleanup and fixes

config/stunnel/stunnel.inc, config/stunnel/stunnel.xml, config/stunnel/stunnel_certs.xml, pkg_config.10.xml
stunnel.xml
- Update copyright header
- Indentation fixes
- Nuke useless chmods for default permissions and useless comments
- Descriptions cosmetics
stunnel_certs.xml
- Update copyright header
- Nuke useless comments
- Descriptions cosmetics
stunnel.inc
- Add missing copyright header
- Fix stunnel_delete() - missing dots after filename
- Use start_service() and stop_service()
- Put JS between CDATA
- No need to unlink service rc script manually on uninstall
=> stunnel - code style fixes

config/squid3/34/squid.inc, pkg_config.10.xml
Also, use platform_booting() for boot check.
@marcelloc - care to take a look as well? :wink:
=> squid3 - use install_cron_job() instead of reimplementing it, fix boot checks

config/sarg/sarg.inc, config/sarg/sarg.php, config/sarg/sarg.priv.inc, config/sarg/sarg.template, config/sarg/sarg.xml, config/sarg/sarg_about.php, config/sarg/sarg_frame.php, config/sarg/sarg_realtime.php, config/sarg/sarg_reports.php, config/sarg/sarg_schedule.xml, config/sarg/sarg_sorttable.js, config/sarg/sarg_sync.xml, config/sarg/sarg_users.xml, pkg_config.10.xml
sarg.xml
- Nuke unused custom_php_(de)install_command
- Fix file permissions
- Make descriptions readable and improve English.
sarg_users.xml
- Nuke unused custom_php_(de)install_command
- Make descriptions readable and improve English
sarg_schedule.xml
- Nuke unused custom_php_(de)install_command
- Nuke some nonsensical extra menu under Diagnostics
- Fix file permissions
- Make descriptions readable and improve English.
sarg_schedule.xml
- Nuke unused custom_php_(de)install_command
- Description cosmetics
sarg.inc
- Code style and …
=> sarg - code style cleanup and fixes

config/squid3/34/squid.inc, pkg_config.10.xml
- The boot check got inverted (obvious brainfart)
- Regarding pinger, the permissions that 4510 (-r-s--x---) root:squid in the (PBI) package. Since we are messing with the GID depending on pfSense version, need to chgrp this to SQUID_GID.
=> squid3 - fix inverted boot check, another attempt to fix pinger (Bug #5114)

config/servicewatchdog/services_servicewatchdog.php, config/servicewatchdog/services_servicewatchdog_add.php, config/servicewatchdog/servicewatchdog.inc, config/servicewatchdog/servicewatchdog.xml, config/servicewatchdog/servicewatchdog_cron.php, pkg_config.10.xml, pkg_config.8.xml, pkg_config.8.xml.amd64
services_servicewatchdog.php
- Update copyright header and some XHTML cosmetics.
services_servicewatchdog_add.php
- Update copyright header, code style cosmetics.
servicewatchdog.inc
- Add copyright header
servicewatchdog.xml
- Nuke useless tags
servicewatchdog_cron.php
- Add copyright header
- Fix boot check
=> servicewatchdog - code style fixes

config/vhosts/vhosts.inc
Configuring an HTTPS vhost there is an error on line 589 because the function write_rcfile() is defined in /etc/inc/service-utils.inc and must be included to work correctly.
=> Included 'service-utils.inc' to fix Call to undefined function write_rcfile()

pkg_config.8.xml, pkg_config.8.xml.amd64
The compatible Snort VRT rules version can no longer be downloaded (and the ruleset version is hardcoded for each Snort version) making the package completely useless. https://www.snort.org/eol
=> Remove Snort package for 2.1.x

config/apache_mod_security/apache_mod_security.inc, config/apache_mod_security/apache_mod_security.xml, config/apache_mod_security/apache_mod_security_settings.xml, config/apache_mod_security/apache_mod_security_view_logs.php, pkg_config.10.xml, pkg_config.8.xml, pkg_config.8.xml.amd64
apache_mod_security.xml
- Fix install and uninstall
- Move the fetch junk to additional_files_needed
- Add input validation
- Improve descriptions and other cosmetics
apache_mod_security_settings.xml
- Add input validation
- Remove no-op/useless tags
- base64_encode() the textarea fields
- Improve descriptions and other cosmetics
apache_mod_security.inc.php
- Fix install and uninstall
- Fix service start/stop/reload and rc file
- Fix broken path to apache config
- Nuke completely broken input "validations"
- Add some actually useful input validations
- Fix whole lot of broken paths in httpd.conf
- Fix textarea config handling
- Nuke no-op junk
apache_mod_security_view_logs.php
- Valid …
=> apache_mod_security - pfSense 2.1.x and 2.2.x and other fixes

config/ntopng/ntopng.inc, pkg_config.10.xml, pkg_config.8.xml, pkg_config.8.xml.amd64
Put $ntopng_config into globals, might fix the service restart after package reinstall...
Note: If someone's going to rebuild the PBIs for https://redmine.pfsense.org/issues/4831 in a reasonable timeframe, this one can definitely wait for that. :wink:
=> ntopng - fix up 2.1.x vs. 2.2.x PBI mess, make $ntopng_config global in ntopng_sync_package()

config/squid3/34/squid.inc, config/squid3/34/squid_cache.xml, pkg_config.10.xml
- move min/max_object_size directives (Bug #5154)
- fix typo breaking squidantivirus XMLRPC sync (Bug #4452)
- make the YouTube caching no-op since it is broken (Bug #3847) and not working anyway because of how YT works (http://wiki.squid-cache.org/ConfigExamples/DynamicContent/YouTube#Discussion)
=> squid3 - multiple fixes (Bug #5154, Bug #4452, Bug #3847)

config/squid3/31/squid.inc, config/squid3/33/squid.inc, config/squid3/33/squid_cache.xml, pkg_config.8.xml, pkg_config.8.xml.amd64
This is for 2.1.x
- move min/max_object_size directives (Bug #5154)
- fix typo breaking squidantivirus XMLRPC sync (Bug #4452)
- make the YouTube caching no-op since it is broken (Bug #3847) and not working anyway because of how YT works (http://wiki.squid-cache.org/ConfigExamples/DynamicContent/YouTube#Discussion)
=> squid3/squid3-dev - multiple fixes (Bug #5154, Bug #4452, Bug #3847)

config/havp/havp.inc, config/havp/havp.xml, pkg_config.10.xml, pkg_config.8.xml, pkg_config.8.xml.amd64
Use filter_rules_needed in XML; directly messing with /tmp/rules.debug and pfctl is certainly not the way to go.
Also fix some clamav-related paths (related to Bug #5157)
=> havp - fix completely broken firewall rules handling (Bug #1561), fix clamav paths (Bug #5157), disable on nanobsd

config/autoconfigbackup/autoconfigbackup.inc, config/autoconfigbackup/autoconfigbackup.php, config/autoconfigbackup/autoconfigbackup.xml, config/autoconfigbackup/autoconfigbackup_backup.php, config/autoconfigbackup/autoconfigbackup_stats.php, config/autoconfigbackup/crypt_acb.php, config/autoconfigbackup/parse_config_upload.inc, config/autoconfigbackup/parse_config_upload.php, config/autoconfigbackup/upload_config_filter.php
**N.B. I cannot test this at all without subscription account. Also, there are some clearly whacky cases like intentionally missing closing PHP tags etc. Kindly test yourself before commit. You have been warned.** :stuck_out_tongue_closed_eyes: 
autoconfigbackup.inc
- Update copyright header
- Code style and whitespace fixes
- Use platform_booting()
- Replace backticks with shell_exec()
- Move custom_php_resync_config_command() function from XML to autoconfigbackup.inc and give it an unique prefix
- Also give an unique prefix to custom_php_validation_command()
autoconfigbackup.php
- Code style and whitespace fixes
- Replace deprecated split() with explode(); still one split() occurrence left - cannot be simply replaced with explode() since that changes the output …
=> autoconfigbackup - code style fixes

config/squid3/34/squid.inc, config/squid3/34/squid.xml, config/squid3/34/squid_antivirus.xml, config/squid3/34/squid_cache.xml, config/squid3/34/squid_reverse_redir.xml, config/squid3/34/squid_reverse_sync.xml, config/squid3/34/squid_reverse_uri.xml, config/squid3/34/squid_sync.xml, config/squid3/34/swapstate_check.php, pkg_config.10.xml
- Put additional safety checks on cachedir and logdir handling
- Don't leave orphaned cache dirs around
- Better out-of-the-box experience with the AV features (set up sane defaults and do not nag users with confusing input errors)
- Add ClamAV mirrors configuration and cron definition updates
- Add manual AV defs update button to GUI
- Add Google Safe Browsing feature
- Fix C-ICAP so that it actually works
- Some other cleanups and cosmetics
=> squid3 - bugfixes round 2

pkg_config.10.xml, pkg_config.8.xml, pkg_config.8.xml.amd64
This uses same directories as Squid3 for ClamAV, installs duplicate ClamAV service, screws directory permissions for Squid's ClamAV instance and produces general mess. People with Squid3 should use C-ICAP and not this dead thing!
=> Do not allow HAVP to be installed along Squid3

config/squid3/34/squid.inc, config/squid3/34/squid_antivirus.inc, config/squid3/34/squid_antivirus.xml, config/squid3/34/squid_cache.xml, config/squid3/34/swapstate_check.php, pkg_config.10.xml
- Remove 'Clear Cache on Log Rotate' misfeature from local cache settings. This has only been a source of complaints, breakage and confusion, plus was breaking Save on the General tab for people.
- Fix freshclam cronjob frequency handling
=> Squid3 - cronjob handling fixes

config/haproxy1_5/www/haproxy_listeners.php
With the current version of haproxy1_5 package, I have this behavior in the interface when having shared frontends (in the frontends section) :
With the patch I get something more normal :
=> haproxy1_5: remove weird visibility:hidden when a listener is secondary

config/squid3/34/squid.xml
Seriously, people? It cannot handle this and mangles things to includesquid_antivirus_status.inc and  widgetssquid_antivirus_status.widget.php? Kindly fix the thing.
=> Fix the package manager idiocy with trailing slash

config/avahi/avahi.inc
Basically if I wanted to publish services via Avahi, I have to check "Disable publishing" and "Disable User Service Publishing", because they operate backwards compared to the description in the web-gui.
This minor fix should change it so it operates according to the description.
=> Avahi - Logic for publishing was swapped.  disable checkbox was enabling & vice-versa

config/sshdcond/sshdcond.inc, config/sshdcond/sshdcond.priv.inc, config/sshdcond/sshdcond.xml, config/sshdcond/sshdcond_sync.xml, pkg_config.10.xml, pkg_config.8.xml, pkg_config.8.xml.amd64
- Add privileges configuration to sshdcond package
**Improve XMLRCP sync**
- Add CARP/HA sync option
- Add port/protocol selection
- Add timeout setting
=> sshdcond - add privileges configuration, improve XMLRPC sync

config/squid3/34/squid.inc, config/squid3/34/squid_reverse_sync.xml, config/squid3/34/squid_sync.xml, pkg_config.10.xml
- Fix CARP/HA sync option
- Add protocol/port selection
=> squid3 - XMLRPC fixes and improvements

config/squid3/31/squid.inc, config/squid3/33/squid.inc, pkg_config.8.xml, pkg_config.8.xml.amd64
The config option used has not existed since pfSense 2.1 (config version 084).
=> squid3/squid3-dev - fix XMLRPC sync with CARP/HA

config/freeradius2/freeradius.inc, config/freeradius2/freeradiussync.xml, pkg_config.10.xml, pkg_config.8.xml, pkg_config.8.xml.amd64
- CARP/HA (auto) option has never worked since pfSense 2.1 due to outdated system settings location being checked
- Also fix CARP/HA protocol/port selection
- Do some better validations (IP/hostname, port, password) before attempting to sync
- Handle IPv6 addresses for sync target
- Do not attempt to run XMLRPC sync on boot
=> freeradius2 - XMLRPC sync fixes

config/sarg/sarg.inc, config/sarg/sarg_sync.xml, pkg_config.10.xml, pkg_config.8.xml, pkg_config.8.xml.amd64
- CARP/HA (auto) option has never worked since pfSense 2.1 due to outdated system settings location being checked
- Also fix CARP/HA protocol/port selection
- Do some better validations (IP/hostname, port, password) before attempting to sync
- Handle IPv6 addresses for sync target
=> sarg - XMLRPC sync fixes

config/snort/snort.inc, config/snort/snort_sync.xml, pkg_config.10.xml
- Fix CARP protocol/port selection
- Properly disable 'Start Snort' for CARP/HA targets
- Do some validations (IP/hostname, port, password) before attempting to sync
- Handle IPv6 addresses for sync target
- The enable checkbox was not being used at all
- The foreach loop skipped all remaining targets if one was misconfigured, due to the 'return' in there
- Do some code style cleanups and polish log messages a bit while here
=> snort - XMLRPC sync fixes

config/suricata/suricata.inc, config/suricata/suricata_sync.xml, pkg_config.10.xml, pkg_config.8.xml, pkg_config.8.xml.amd64
- the CARP (auto) option has never worked due to outdated system settings location being checked
- the enable checkbox was not being used at all
- the foreach loop skipped all remaining targets if one was misconfigured, due to the 'return' in there
- polish log messages a bit
=> suricata - XMLRPC sync fixes round two

config/filer/filer.inc, config/filer/filer_sync.xml, pkg_config.10.xml, pkg_config.8.xml, pkg_config.8.xml.amd64
- Add CARP/HA sync option
- Add protocol/port selection
- Add timeout setting
=> Filer - XMLRPC sync fixes and improvements

config/haproxy-legacy/haproxy.inc, pkg_config.8.xml, pkg_config.8.xml.amd64
The config option used has not existed since pfSense 2.1 (config version 084).
=> haproxy-legacy - Fix XMLRPC sync with CARP/HA

config/apache_mod_security-dev/apache_mod_security.inc, config/apache_mod_security-dev/apache_mod_security_sync.xml, pkg_config.10.xml, pkg_config.8.xml, pkg_config.8.xml.amd64
- Fix CARP/HA sync option (port/protocol)
- Add protocol/port selection
- Nuke obsolete pfSense 2.0 cruft
=> apache_mod_security-dev - XMLRPC sync fixes and improvements

pkg_config.10.xml
- Add warnings about ClamAV conflicts among Squid3, Dansguardian, Mailscanner and HAVP packages.
- Clean up/improve some descriptions
- Use unified ALPHA/BETA/RC/RELEASE status for packages.
- Sanitize package categories a bit.
- Improve some post-install info messages.
=> Add warnings about conflicting packages, some cleanups

config/suricata/suricata.xml, config/suricata/suricata_barnyard.php, config/suricata/suricata_check_for_rule_updates.php, config/suricata/suricata_flow_stream.php, config/suricata/suricata_generate_yaml.php, config/suricata/suricata_global.php, config/suricata/suricata_interfaces_edit.php, config/suricata/suricata_migrate_config.php, config/suricata/suricata_post_install.php, config/suricata/suricata_yaml_template.inc, pkg_config.10.xml
Suricata 2.0.9 pkg v2.1.9
===================
This updates the Suricata GUI package to v2.1.9 and the binary PBI package to v2.0.9.  The [Change Log for Suricata 2.0.9 is here](http://suricata-ids.org/2015/09/25/suricata-2-0-9-available/).  In addition to the upstream changes, the custom *alert-pf* blocking module sports a new automatic whitelisting feature for all firewall interface IP addresses.  During initialization of the *alert-pf* module, an interface monitoring thread is started to subscribe to and monitor FreeBSD kernel routing messages for changes to interface IP addresses.  An internal in-memory whitelist is maintained of all firewall interface IP addresses to prevent blocking of interface IP addresses.  This feature is particularly helpful to users with frequently changing WAN …
=> Update Suricata GUI package to 2.1.9 and PBI binary to 2.0.9

pkg_config.10.xml
Update *build_options* values for Suricata and Snort PBIs to reflect recent changes in the ports tree.
=> Fix for Snort and Suricata <build_options>.

config/ntop2/ntop.inc, config/ntop2/ntop.priv.inc, config/ntop2/ntop.xml, pkg_config.10.xml, pkg_config.8.xml, pkg_config.8.xml.amd64
- Split PHP code to a separate inc file
- Make it possible to disable ntop without uninstalling
- Add Keep Data/Settings feature
- Fix flipped 'Allow merging interfaces' meaning
- Code style cleanups
=> ntop - package fixes and cleanups

config/checkmk-agent/checkmk.inc, config/checkmk-agent/checkmk.xml, config/checkmk-agent/checkmk_sync.xml
- Fix inetd handling which was completely broken on pfSense 2.2.x (Bug #4288)
- Detect junk left over by previous versions and log appropriate instructions if needed
- Fix completely broken input validations
- Some other cleanups
- Fix CARP/HA XMLRPC sync option
- Add enable/disable checkbox per XMLRPC replication target
- Add protocol/port selection to XMLRPC
- Fix literal IPv6 handling for XMLRPC sync targets
=> checkmk-agent - fix inetd handling, improve XMLRPC sync, cleanup

config/systempatches/patches.inc, pkg_config.10.xml, pkg_config.8.xml, pkg_config.8.xml.amd64
This should work both on 2.2+ using download_file() and on 2.1.x using download_file_with_progress_bar() instead (because the former did not exist in pfsense-utils.inc yet). Seems better to me than copying over the entire function.
=> systempatches - make fetch work if pfsense is behind proxy (fixes bug #4369)

config/squidGuard/squidguard.inc, config/squidGuard/squidguard.xml, config/squidGuard/squidguard_sync.xml, pkg_config.10.xml, pkg_config.8.xml, pkg_config.8.xml.amd64
**RAM disks handling**
- force users to disable any ramdisks on full installs (even from a quick look, there are definitely more issues with this than just blacklists DB)
- force users to disable blacklists feature on nanobsd (still a whole lot better than marking the package as noembedded)
This has been broken for years (Bug #4608) and got nowhere.
**XMLRPC sync**
- Fix CARP/HA sync option (port/protocol)
- Honor enable/disable checkboxes
=> squidGuard -  XMLRPC fixes; add checks for ramdisks, force disable blacklists usage on nanobsd (Bug #4608)

config/squidGuard-devel/squidguard.inc, config/squidGuard-devel/squidguard.xml, config/squidGuard-devel/squidguard_sync.xml, pkg_config.10.xml, pkg_config.8.xml, pkg_config.8.xml.amd64
**RAM disks handling**
- force users to disable any ramdisks on full installs (even from a quick look, there are definitely more issues with this than just blacklists DB)
- force users to disable blacklists feature on nanobsd (still a whole lot better than marking the package as noembedded)
This has been broken for years (Bug #4608) and got nowhere.
**XMLRPC sync**
- Fix CARP/HA sync option (port/protocol)
- Honor enable/disable checkboxes
=> squidGuard-devel - XMLRPC fixes; add checks for ramdisks, force disable blacklists usage on nanobsd (Bug #4608)

config/squid3/34/squid.inc, config/squid3/34/squid_cache.xml, pkg_config.10.xml
Avast/Symantec have been completely no-op and useless for years since AV updates for those are streamed to clients hundreds times every day. Suspect same story for Avira. The WU refresh_patterns was broken and don't work reliably anyway. People can define their own patterns if needed without maintenance burden for package maintainers.
=> Squid3 - remove broken dynamic caching refresh_patterns

config/ipguard/ipguard.inc, config/ipguard/ipguard.priv.inc, config/ipguard/ipguard.xml, config/ipguard/ipguard_sync.xml, pkg_config.10.xml, pkg_config.8.xml, pkg_config.8.xml.amd64
- Add CARP/HA sync option
- Add protocol/port selection
- Add timeout setting
- Some code style touches while here
=> ipguard - add privileges configuration, XMLRPC sync fixes and improvements

config/snort/snort.inc, config/snort/snort.xml, config/snort/snort_check_for_rule_updates.php, config/snort/snort_conf_template.inc, config/snort/snort_defs.inc, config/snort/snort_frag3_engine.php, config/snort/snort_ftp_client_engine.php, config/snort/snort_ftp_server_engine.php, config/snort/snort_generate_conf.php, config/snort/snort_httpinspect_engine.php, config/snort/snort_interfaces_edit.php, config/snort/snort_migrate_config.php, config/snort/snort_post_install.php, config/snort/snort_preprocessors.php, config/snort/snort_stream5_engine.php, pkg_config.10.xml
Snort 2.9.7.6 pkg v3.2.9
==================
This updates the Snort binary to v2.9.7.6 and the pfSense GUI package to v3.2.9.  This update adds support for two new HTTP_INSPECT options and enables logging of IPv6 address in Unified2 logs as extra-data.  There are four minor bug fixes included with this update.
New Features
------------------
1.  Added support for the *decompress_swf* and *decompress_pdf* options for the HTTP_INSPECT preprocessor.  These options decompress Shockwave Flash and Adobe PDF files so they can be further inspected.  The new settings are available on the HTTP_INSPECT Engines dialog on the PREPROCESSORS tab.
2.  IPv6 addresses are now logged as extra-data when Unified2 log output is enabled with Barnyard2.
Bug Fixes
-------------
1.  Tidy up output messages …
=> Update Snort binary to v2.9.7.6 and GUI package to v3.2.9

config/pfblockerng/pfblockerng_install.inc
This commit fixes a PHP file caching issue with the Installation code for the MaxMind Downloads.
The new code will also skip downloading the MaxMind files on a Re-Install if the files have been previously downloaded. (Reduce bandwidth on MaxMind's Servers).
No version bump needed for this installation code.
=> pfBlockerNG - Installation code caching fix

config/pfblockerng/pfblockerng.inc, config/pfblockerng/pfblockerng.php, config/pfblockerng/pfblockerng_dnsbl.xml, config/pfblockerng/pfblockerng_v4lists.xml, config/pfblockerng/pfblockerng_v6lists.xml, pkg_config.10.xml
* Add missing ['host'] key to $host variable.
* Add query if download failure is due to DNSBL Block.
* Change text from IDS to IPS.
* Remove International, special or space characters from 'Alias Custom' names.
* Cosmetic text fixes.
=> pfBlockerNG - Improve download failure function

config/apache_mod_security-dev/apache_mod_security.inc, config/bind/bind.inc, config/checkmk-agent/checkmk.inc, config/dansguardian/dansguardian.inc, config/filer/filer.inc, config/freeradius2/freeradius.inc, config/haproxy-devel/pkg/haproxy_xmlrpcsyncclient.inc, config/haproxy1_5/pkg/haproxy_xmlrpcsyncclient.inc, config/ipguard/ipguard.inc, config/mailscanner/mailscanner.inc, config/pfblockerng/pfblockerng.inc, config/postfix/postfix.inc, config/postfix/postfix.php, config/sarg/sarg.inc, config/snort/snort.inc, config/squid3/34/squid.inc, config/squid3/34/squid_antivirus.inc, config/squid3/34/squid_js.inc, config/squid3/34/squid_reverse.inc, config/squidGuard-devel/squidguard.inc, config/squidGuard/squidguard.inc, config/sshdcond/sshdcond.inc, config/suricata/suricata.inc, config/tinydns/tinydns.inc, config/varnish3/varnish.inc, pkg_config.10.xml
This is mainly in reaction to recent breakage on 2.3 caused by removing `require_once("xmlrpc.inc");` from pkg-utils.inc, but I think it's better to state the requirements explicitly rather than rely on getting the functions included indirectly from elsewhere.
(BTW, https://github.com/pfsense/pfsense/pull/2102 can be reverted once this gets merged and synced to the https://github.com/pfsense/FreeBSD-ports repo, after that none of the packages viable for 2.3 would rely on it any more.)
=> Add explicit includes to a bunch of packages

config/squid3/34/squid.inc, config/squid3/34/squid.xml, pkg_config.10.xml
This "feature" has been broken for almost a year without anyone noticing; see https://redmine.pfsense.org/issues/5594 for details. Remove this junk until a saner alternative is available. System Patches is the way to go until that happens if someone really requires that.
On upgrade, an attempt to restore a backup will be made, and appropriate notice filed (and logged). There are also GUI instructions left in place of the original checkbox.
=> Squid3 - Remove the broken patch CP feature (Bug #5594)

config/pfblockerng/pfblockerng.inc, config/pfblockerng/pfblockerng.php, config/pfblockerng/pfblockerng.xml, config/pfblockerng/pfblockerng_install.inc, config/pfblockerng/pfblockerng_top20.xml, pkg_config.10.xml
* Bump version to 2.0.3
* Add missing $g global setting.
* Explicitly define $pfb variables in the install file (php caching issue)
* Change DNSBL start_service() to restart_service()
* Add    **set_time_limit(0);**   to DNSBL php daemon session
* Add/Change syslog notice messages.
* Add 'Alias_Native' option to TOP20 Tab.
=> pfBlockerNG - Mods

config/pfblockerng/pfblockerng.inc, config/pfblockerng/pfblockerng.xml, config/pfblockerng/pfblockerng_dnsbl_lists.xml, config/pfblockerng/pfblockerng_install.inc, config/pfblockerng/pfblockerng_threats.php, config/pfblockerng/pfblockerng_update.php, pkg_config.10.xml
* Fix 'Match Outbound' rule variable name
* Remove duplicate Alexa variable as its already in pfb_global()
* Determine if a DNSBL background reload is running before updating DNSBL
* Change "${cmd}"  variable name to  "{$cmd}"
* Add $pfb['ccdir'] explicitly due to file caching issue.
* Fix dShield URL
* Add tcpiputils to DNSBL Domain threat lookup
* Add log size settings (5000 & 10000 lines) for limited storage installations.
* Add Paypal link
* Remove extra whitespace
=> pfBlockerNG - version 2.0.4

config/tftp2/tftp.inc, config/tftp2/tftp.xml, config/tftp2/tftp_files.php, pkg_config.10.xml, pkg_config.8.xml, pkg_config.8.xml.amd64
1) If the user presses Save when there was no interface selected, and
the user has still not selected an interface, then do not attempt to
unset() tftpdinterface in the config when it is already unset.
2) If the user does backup/restore or other similar stuff when the
tftpboot directory has no files in it, then do not do chmod of the
(non-existent) files. This avoids a "No such file or directory" message
being logged.
This is for 2.1.* and 2.2.* - I will also make an equivalent PR in the other repo for 2.3
=> Redmine #5727 TFTP protect against empty stuff

config/pfblockerng/index.php, config/pfblockerng/pfblockerng.inc, config/pfblockerng/pfblockerng.js, config/pfblockerng/pfblockerng.php, config/pfblockerng/pfblockerng.sh, config/pfblockerng/pfblockerng.widget.php, config/pfblockerng/pfblockerng.xml, config/pfblockerng/pfblockerng_alerts.php, config/pfblockerng/pfblockerng_alerts_ar.php, config/pfblockerng/pfblockerng_dnsbl.xml, config/pfblockerng/pfblockerng_dnsbl_easylist.xml, config/pfblockerng/pfblockerng_dnsbl_lists.xml, config/pfblockerng/pfblockerng_extra.inc, config/pfblockerng/pfblockerng_install.inc, config/pfblockerng/pfblockerng_log.php, config/pfblockerng/pfblockerng_sync.xml, config/pfblockerng/pfblockerng_threats.php, config/pfblockerng/pfblockerng_top20.xml, config/pfblockerng/pfblockerng_update.php, config/pfblockerng/pfblockerng_v4lists.xml, config/pfblockerng/pfblockerng_v6lists.xml, pkg_config.10.xml
* Add TLSv1.1 to cURL SSL Options
* Improve 'Max daily download failure threshold' feature
* Improve function pfbng_text_area_decode() add $mode variable to account for '#' comment lines in DNSBL Suppression Alias
* Improve dnsbl_suppression() function
* Implement 'Advanced Outbound Firewall Rules' customization options.
* Implement 'Advanced In/Outbound Firewall Rules' - Invert Source/Destination options
* Implement 'Advanced In/Outbound Firewall Rules' - Gateway options
* 'Advanced In/Outbound Firewall Rules' - Force any Invert Source/Destination Alias to use 'Alias Native' settings
* Allow Loopback and RFC1918 addresses in any Alias Custom List.
* Improve GZIP archive extraction function
* Re-factor Tracker IDs. (Convert all unique Alias details (via ascii table number) and return a 10 …
=> pfBlockerNG - version 2.0.5

config/backup/backup.php
Use the correct escaping for this input. Thus preventing RCE.
=> Use the correct escaping
