pfsense/pfsense-packages

config/squidGuard-devel/squidguard_configurator.inc
config/squidGuard/squidguard_configurator.inc
pkg_config.10.xml
pkg_config.8.xml
pkg_config.8.xml.amd64

update squidguard squid.conf syntax
this will allow it to run with either squid2 and squid3, no patching for squid 3 to work
https://forum.pfsense.org/index.php?topic=73640
https://forum.pfsense.org/index.php?topic=86701.msg475980#msg475980

update squidguard squid syntax

---

pkg_config.10.xml

Also removes pfBlocker from 2.2 list.

PfblockerNG - Release package to 2.2

---

config/zabbix2/zabbix2.inc
pkg_config.10.xml

A small change for not break users on pfSense 2.1.
Bump version.

zabbix2 - update packages - second step

---

config/tinc/tinc.inc

tinc, fix2 for re-installation, while performing a pfSense firmware upgrade.

tinc, fix2 for re-installation, while performing a pfSense firmware upgrade.

---

config/haproxy-devel/haproxy.inc
config/haproxy-devel/haproxy_global.php
config/haproxy-devel/pkg/haproxy_upgrade_config.inc
pkg_config.10.xml
pkg_config.8.xml
pkg_config.8.xml.amd64

haproxy-devel,bump 0.19, fixed carp monitoring and added conversion from old carp-monitor config

haproxy-devel,bump 0.19, fixed carp monitoring and added conversion from old carp-monitor config

---

config/pfblockerng/pfblockerng.inc
config/pfblockerng/pfblockerng.xml
config/pfblockerng/pfblockerng_alerts.php
pkg_config.10.xml

1) Some Cosmetic Changes
2) Improve IPv6 Regex
3) Add '0.0.0.0/32' to the Suppression array
4) Move the "Keep Settings" Checkbox below the "Enable pfBNG" checkbox.
5) Redmine Issue no. 4410. Skip over Comment Lines
6) Improve Efficiency of Alerts Tab

pfBlockerNG_021015_1

---

pkg_config.8.xml
pkg_config.8.xml.amd64

just for fix the installation problem

zabbix - revert package name for pfSense 2.1

---

config/apcupsd/apcupsd.xml
config/apcupsd/apcupsd_mail.php
pkg_config.10.xml
pkg_config.8.xml
pkg_config.8.xml.amd64

- alter reference for PHPMailer. (PHPMailer was updated on mailreport package)
- bump version

apcupsd - fix e-mail notifications

---

config/haproxy-devel/pkg/haproxy_utils.inc
config/haproxy1_5/haproxy.xml
config/haproxy1_5/pkg/haproxy.inc
config/haproxy1_5/pkg/haproxy_htmllist.inc
config/haproxy1_5/pkg/haproxy_socketinfo.inc
config/haproxy1_5/pkg/haproxy_upgrade_config.inc
config/haproxy1_5/pkg/haproxy_utils.inc
config/haproxy1_5/pkg/haproxy_utils.inc.bak
config/haproxy1_5/pkg/haproxy_xmlrpcsyncclient.inc
config/haproxy1_5/pkg/pkg_haproxy_tabs.inc
config/haproxy1_5/www/haproxy_files.php
config/haproxy1_5/www/haproxy_global.php
config/haproxy1_5/www/haproxy_listeners.php
config/haproxy1_5/www/haproxy_listeners_edit.php
config/haproxy1_5/www/haproxy_pool_edit.php
config/haproxy1_5/www/haproxy_pools.php
config/haproxy1_5/www/haproxy_stats.php
config/haproxy1_5/www/haproxy_templates.php
config/haproxy1_5/www/javascript/haproxy_geturl.js
config/haproxy1_5/www/shortcuts/pkg_haproxy.inc
config/haproxy1_5/www/widgets/widgets/haproxy.widget.php
pkg_config.10.xml
pkg_config.8.xml
pkg_config.8.xml.amd64

haproxy-1_5, create 'release' package from haproxy-devel base, to have a 'production' stable version

haproxy-1_5 release package

---

config/pfblockerng/geoipupdate.sh
config/pfblockerng/pfblockerng.inc
config/pfblockerng/pfblockerng.js
config/pfblockerng/pfblockerng.php
config/pfblockerng/pfblockerng.sh
config/pfblockerng/pfblockerng.widget.php
config/pfblockerng/pfblockerng.xml
config/pfblockerng/pfblockerng_alerts.php
config/pfblockerng/pfblockerng_diag_dns.php
config/pfblockerng/pfblockerng_log.php
config/pfblockerng/pfblockerng_sync.xml
config/pfblockerng/pfblockerng_top20.xml
config/pfblockerng/pfblockerng_update.php
config/pfblockerng/pfblockerng_v4lists.xml
config/pfblockerng/pfblockerng_v6lists.xml
pkg_config.10.xml

- Mods to pfblockerng_diag_dns.php to align with changes to pfSense diag_dns.php
- (c)2015 Mods
- When Suppression Alias is cleared, the suppression txt file was not cleared. Fixed.
- Bump to **v1.06** and change Status to "**Stable**"

pfBlockerNG - v1.06

---

config/freeradius2/freeradius.inc
pkg_config.10.xml
pkg_config.8.xml
pkg_config.8.xml.amd64

Prevent radiusd from being started multiple times #4337

---

config/spamd/spamd.inc
config/spamd/spamd_db.php
config/spamd/spamd_settings.xml
pkg_config.10.xml
pkg_config.8.xml
pkg_config.8.xml.amd64

spamd, fix spamtrap and blacklist buttons, fix startup on pfSense 2.2

spamd, fix spamtrap and blacklist buttons, fix startup on pfSense 2.2

---

config/checkmk-agent/checkmk.inc

HEAD Version is considered BETA, Stable Release is v1.2.6.
See here: http://mathias-kettner.de/check_mk_download.html

Use stable release of check_mk_agent (v1.2.6)

---

config/squidGuard/squidguard_configurator.inc
pkg_config.10.xml
pkg_config.8.xml
pkg_config.8.xml.amd64

corrected the path to the squid binary
should be SQUID_BASE instead of SQUID_LOCALBASE

correction of path to squid binary

---

config/squidGuard/squidguard.inc

If empty ACL list - pkg_edit.inc show error string.

Squidguard fix ACL order problem

---

config/squid3/34/squid_clwarn.php
config/squid3/34/squid_monitor.php
config/squid3/34/squid_monitor_data.php
pkg_config.10.xml

this writes a logfile when a virus was found
and displays the log on the "realtime" tab

squid3: added virus log

---

config/zabbix-agent-lts/zabbix-agent-lts.xml
config/zabbix-proxy-lts/zabbix-proxy-lts.inc
config/zabbix-proxy-lts/zabbix-proxy-lts.xml
pkg_config.10.xml

the problem with restart service happens only with zabbix_proxy.

zabbix_lts - fix resync problem

---

config/haproxy-devel/pkg/haproxy.inc
config/haproxy-devel/pkg/haproxy_utils.inc
config/haproxy-devel/www/haproxy_listeners_edit.php
pkg_config.10.xml

haproxy-devel, new functionality SSL OCSP stapling for haproxy
-fix server dns resolving in case a CNAME is used.

haproxy-devel, new functionality SSL OCSP stapling for haproxy

---

config/freeradius2/freeradiuseapconf.xml

Fix typo in freeradiuseapconf.xml

---

config/haproxy-devel/pkg/haproxy.inc
config/haproxy-devel/pkg/haproxy_utils.inc
config/haproxy-devel/www/haproxy_listeners_edit.php
config/haproxy-devel/www/haproxy_pool_edit.php
pkg_config.10.xml

haproxy-devel, fix dns resolving dns_get_record does not properly resolve if not all requested types are present..

haproxy-devel, fix dns resolving dns_get_record does not properly resolve if not all requested types are present..

---

config/ntopng/ntopng.xml
pkg_config.10.xml
pkg_config.8.xml
pkg_config.8.xml.amd64

ntopng, fix mkdir warning while booting, use safe_mkdir

ntopng, fix mkdir warning while booting, use safe_mkdir

---

config/vnstat2/vnstat2.inc
config/vnstat2/vnstat2.xml
config/vnstat2/vnstati.xml
config/vnstat2/vnstatoutput.xml
config/vnstat2/www/diag_vnstat.php
config/vnstat2/www/diag_vnstat2.php
config/vnstat2/www/vnstati.php
pkg_config.10.xml
pkg_config.8.xml
pkg_config.8.xml.amd64

Cleaned up whitespace, formatted PHP code and fixed #4834.

vnstat2 fix for #4834 and code formatting

---

config/siproxd/siproxd.inc
pkg_config.10.xml

Listening port redirect rule pulling wrong tag from siproxdsettings in config.xml

Fix Bug #4561

---

config/checkmk-agent/checkmk.xml
pkg_config.10.xml

Typo fixes plus do not mark optional setting as required.

Cosmetic fixes for Bug #4085

---

config/rrd-summary/rrd-summary.xml
config/rrd-summary/status_rrd_summary.php
pkg_config.10.xml

Remove useles stuff from xml, remove bogus chmod 077, fix code style. Fix XHTML validation.
P.S. Kindly ignore the incorrect 0836ad2 commit message for rrd-summary.xml ;)

rrd-summary - code style and other fixes

---

config/arping/arping.inc
config/arping/arping.xml
pkg_config.10.xml

1. Added options:
* make count configurable (defaults to 3)
* add interface selection
2.  Command options are shown before the output.
3. Added a Back button after command output, to go back to ARPing menu. Button is also displayed after failed input validation.
1. Mark pinghost field as required.
2. Remove unused tags and functions.
3. Remove pointless tab from the GUI.
4. Fix indentation.
5. Developer style guide fixes.

arping - multiple improvements plus code style fixes

---

config/tinydns/tinydns.inc
config/tinydns/tinydns.xml
pkg_config.10.xml

Bug #4555 - Tiny DNS: Service does not start

---

config/arping/arping.xml

That bogus > needs to go away.

arping.xml - fix menu entry

---

config/nmap/nmap.inc
config/nmap/nmap.xml
pkg_config.10.xml

Also:
- nuke chmod 077, fix version and remove unused tags in xml
- add back button to the output to go back to nmap menu
- use safe_mkdir

nmap - code style fixes, add copyright headers

---

config/openvpn-client-export/openvpn-client-export.inc
config/openvpn-client-export/openvpn-client-export.xml
config/openvpn-client-export/openvpnexport.inc
config/openvpn-client-export/vpn_openvpn_export.php
config/openvpn-client-export/vpn_openvpn_export_shared.php
pkg_config.10.xml

- add standard XML and copyright headers
- remove bunch of 077 chmods
- remove unused tags

openvpn-client-export package - code cleanup and fixes

---

config/openvpn-client-export/openvpn-client-export.inc
config/openvpn-client-export/openvpn-client-export.xml
config/openvpn-client-export/vpn_openvpn_export.php
config/openvpn-client-export/vpn_openvpn_export_shared.php
pkg_config.10.xml

Since doctornoktor did a bunch of this, I thought that I might as well review it also. It seems good to make the packages that are "internally" maintained conform to the code style guide.
I bumped the version so it will be easy for people to see exactly what version of code they are running, even though there is no functional change here.

OpenVPN Client Export code style

---

config/iperf/iperf.xml
config/iperf/iperfserver.xml
pkg_config.10.xml

- Code style
- Descriptions cosmetics
- Use consistent sanitized version

iperf - code style cleanup

---

config/widentd/widentd.xml
pkg_config.10.xml

-  Fix copyright header
-  FIx indentation, code cleanup
-  Add enable/disable checkbox
-  Add input validation (username, sysname, IPv4)
-  Actually make the default values (username, sysname) work, previously nothing was set if left empty
- Fix Bug 3434 by adding custom_php_resync_config_command

widentd - code style and multiple improvements/bugfixes

---

config/blinkled8/blinkled.inc
config/blinkled8/blinkled.xml
pkg_config.10.xml

OK, lets redo this for the *right* package now. Sigh. Perhaps someone could remove the duff package from the master branch and leave just the one that's being used?!
blinkled.xml
- Add copyright headers
- Better service description
blinkled.inc
- Add copyright headers
- use is_process_running() instead of blinkled_running()
- remove blinkled_stop() and blinkled_start in favour of start_service()/stop_service() in order to actually utilize the service in a meaningful way
P.S. Tested and working on Alix. :-P

blinkled - code style fixes and rework

---

config/vnstat2/vnstat2.inc
config/vnstat2/vnstat2.xml
config/vnstat2/vnstati.xml
config/vnstat2/vnstatoutput.xml
config/vnstat2/www/diag_vnstat.php
config/vnstat2/www/diag_vnstat2.php
config/vnstat2/www/vnstat2_img.php
config/vnstat2/www/vnstati.php
pkg_config.10.xml

Code style cleanup, some XHTML fixes etc.

vnstat2 - code style cleanup round 2

---

config/lcdproc/lcdproc.inc

Seems on my copy of this firewall I have to put the physical ip of local machine as localhost name don't work.Then this package works

LCDProc Local host fix

---

config/sudo/sudo.inc
config/sudo/sudo.xml
pkg_config.10.xml

Not much here - the code is really small.

sudo package code style

---

config/backup/backup.inc
config/backup/backup.php
config/backup/backup.xml
config/backup/backup_edit.php
pkg_config.10.xml

I thought I might as well quickly format these little packages also, just so they are done if anyone else ever touches them again. I will look at a couple more like:
blinkled
gwled
LCDproc (maybe)
mailreport
Shellcmd
They seem to be the little packages that are easy and are mostly maintained internally when needed.

Backup package code style

---

config/cron/cron.inc
config/cron/cron.php
config/cron/cron.xml
config/cron/cron_edit.php
pkg_config.10.xml

I don't know what the convention is now about bumping the version for pkg_config 8, so let me know if I need to do that.
No functional change - this is all white space and code style.

Cron package code style

---

config/haproxy1_5/haproxy.xml
pkg_config.10.xml

Updated copyright header and nuked useless unused tags while here.

haproxy1_5 - fix file permissions

---

config/openbgpd/openbgpd.xml
pkg_config.10.xml

Updated copyright header, fixed broken indentation and improved descriptions readability while here.

openbgpd - fix file permissions

---

config/siproxd/siproxd.xml
config/siproxd/siproxdusers.xml
pkg_config.10.xml

Updated copyright header, and improved descriptions readability while here.

siproxd - fix file permissions

---

config/widget-antivirus/antivirus_status.widget.php
config/widget-antivirus/widget-antivirus.xml
pkg_config.10.xml

Fix copyright header while here.

widget-antivirus - fix file permissions

---

config/olsrd/olsrd.inc
config/olsrd/olsrd.xml
pkg_config.10.xml

- Add missing copyright headers
- Fix indentation, nuke useless junk, use consistent version.
**Please, tripple-check the olsrd.inc file!** The badly styled code with zillions of nested foreach() and if() statements and inlined heredocs is anything but readable. :-(

olsrd code style cleanup

---

config/lcdproc/lcdproc.inc
config/lcdproc/lcdproc.xml
config/lcdproc/lcdproc_client.php
config/lcdproc/lcdproc_screens.xml
pkg_config.10.xml

lcdproc.xml
- Add missing copyright header
- Remove useless functions
lcdproc.inc
- Remove useless/unused functions
- Use is_process_running() / stop_service() / restart_service()
- Remove useless config_lock() / config_unlock()
- Indentation and code style fixes
lcdproc_client.php
- Indentation and code style fixes
- Replace backticks with shell_exec()
lcdproc_screens.xml
- Add missing copyright header
- Remove useless/unused functions
- Use consistent version in all XML files

lcdproc - code style fixes

---

config/ladvd/ladvd.inc
config/ladvd/ladvd.xml
config/ladvd/status_ladvd.php
pkg_config.10.xml

ladvd.xml
- Use consistent package version in XML
ladvd.inc
- Fix copyright header and indentation
status_ladvd.php
- XHTML valid code

ladvd - code style fixes

---

config/notes/notes.inc
config/notes/notes.xml
pkg_config.10.xml

notes.xml
- Remove tons of useless garbage
notes.inc
- Remove tons of useless garbage

notes - code cleanup round two

---

config/cron/cron.inc
config/filemgr/filemgr.inc
config/haproxy-legacy/haproxy_global.php
config/haproxy/haproxy_global.php
config/phpservice/phpservice.inc
config/phpsysinfo/phpsysinfo.inc
config/shellcmd/shellcmd.inc
config/spamd/spamd.inc
config/spamd/spamd_db.php
config/tinc/tinc.inc
config/vhosts/vhosts.inc

Should be complete now. (lcdprov-dev handled in #988 and pure-ftpd in #978).

remove useless config_(un)lock calls round two

---

config/routed/routed.inc
config/routed/routed.xml
pkg_config.10.xml

routed.xml
- Fix copyright header and indentation
- Nuke useless comments and empty tags
- Install routed service

routed - code style fixes

---

config/systempatches/patches.inc
config/systempatches/system_patches.php
config/systempatches/system_patches_edit.php
config/systempatches/systempatches.xml
pkg_config.10.xml

systempatches.xml
- Fix copyright header and nuke pointless tags.
patches.inc
- Switch GitHub to HTTPS.
system_patches.php
- Some XHTML fixes
system_patches_edit.php
- Fix copyright header; add missing space.

systempatches - some code style cosmetics

---

config/diag_states_pt/diag_new_states.php
config/diag_states_pt/diag_new_states.xml
pkg_config.10.xml

diag_new_states.xml
Fix copyright header, indentation, permissions, remove useless stuff.
diag_new_states.php
- Code style
- Fix XHTML validation
This is actually pretty impresive well written code. Needs fixing for IPv6 though, the ports are not stripped properly there.

diag_new_states - code style fixes

---

config/lcdproc-dev/lcdproc.inc
config/lcdproc-dev/lcdproc.xml
config/lcdproc-dev/lcdproc_client.php
config/lcdproc-dev/lcdproc_screens.xml
pkg_config.10.xml

lcdproc.xml
- Add missing copyright header
- Fix indentation/whitespace
lcdproc.inc
- Replace bogus boot check with platform_booting()
lcdproc_screens.xml
- Add missing copyright header
- Remove unused function
lcdproc_client.php
- Indentation and code style fixes
- Replace backticks with shell_exec()
- Replace deprecated split() function with explode()

lcdproc-dev - code style fixes

---

config/spamd/spamd.inc
config/spamd/spamd_db.php
config/spamd/spamd_settings.xml
pkg_config.10.xml
pkg_config.8.xml
pkg_config.8.xml.amd64

spamd, allow configuring interface to listen/intercept on & show correct times

spamd, allow configuring interface to listen/intercept on & show correct times

---

config/filemgr/file_manager.php
config/filemgr/filemgr.xml
pkg_config.10.xml

- Get rid of escaping in heredocs plus related fixes so that this actually works.

filemgr - fixes round two

---

config/haproxy-devel/haproxy.xml
config/haproxy-devel/pkg/haproxy.inc
config/haproxy-devel/pkg/haproxy_htmllist.inc
config/haproxy-devel/www/haproxy_files.php
config/haproxy-devel/www/haproxy_global.php
config/haproxy-devel/www/haproxy_pool_edit.php
pkg_config.10.xml
pkg_config.8.xml
pkg_config.8.xml.amd64

haproxy-devel, fix package for pfsense 2.1.5, bump pkg v0.29
-add email settings for 1.6-dev version
-remove call to nonexisting javascript function
-put a maximum height to a table textarea + scrollbar
-remove httpchk from config file when not used

haproxy-devel, fix package for pfsense 2.1.5, bump pkg v0.29

---

config/bandwidthd/bandwidthd.inc
config/bandwidthd/bandwidthd.xml
pkg_config.10.xml

- Re-added a field to manually specify subnets
- Use double quotes instead of single quotes for filter because bandwidthd won't start otherwise
- Fix cronjob install

bandwidthd - re-add custom subnets, fix advanced filter and cron

---

config/quagga_ospfd/quagga_ospfd.inc
config/quagga_ospfd/status_ospfd.php
pkg_config.10.xml

- Fix OSPF authentication - resubmit of #1039 by trendchiller (forum reference https://forum.pfsense.org/index.php?topic=72343.msg394722#msg394722)

quagga_ospfd - fix OSPF authentication, code style

---

config/openbgpd/openbgpd.inc
config/openbgpd/openbgpd_groups.xml
config/openbgpd/openbgpd_neighbors.xml
config/openbgpd/openbgpd_raw.php
config/openbgpd/openbgpd_status.php
pkg_config.10.xml

Code style fixes plus nuke bunch of useless pfSense 1.x cruft.

openbgpd code style fixes

---

config/postfix/postfix.inc
pkg_config.10.xml

- Beyond reinveting the install_cron_job() thing repeatedly, this has been rewriting /etc/crontab directly. Ugh.
- Fix bogus boot check while here.

postfix - fix badly broken cron handling, fix boot check

---

config/havp/antivirus.php
config/havp/havp.xml
config/havp/havp_avset.xml
config/havp/havp_log.php
pkg_config.10.xml

havp - add clamd log tab to GUI

---

config/ipguard/ipguard.inc
config/lcdproc-dev/lcdproc.inc
config/nut/nut.inc
config/sarg/sarg.inc
config/squid/squid.inc
config/sshdcond/sshdcond.inc
pkg_config.10.xml
pkg_config.8.xml
pkg_config.8.xml.amd64

Lets put more of messy legacy cruft back as requested...

Use 2.1.x compatible boot check in bunch of packages

---

config/bacula-client/bacula-client.xml
config/bacula-client/bacula-client_view_config.php
pkg_config.10.xml
pkg_config.8.xml
pkg_config.8.xml.amd64

bacula, fix 'view configuration', bump version 1.0.10

bacula, fix 'view configuration', bump version 1.0.10

---

config/havp/havp.inc
config/havp/havp.xml
pkg_config.10.xml
pkg_config.8.xml
pkg_config.8.xml.amd64

Reference: https://redmine.pfsense.org/issues/5117#note-16

havp - fix templates path

---

config/bacula-client/bacula-client.inc
config/bacula-client/bacula-client.xml
config/bacula-client/bacula-client_view_config.php
pkg_config.10.xml
pkg_config.8.xml
pkg_config.8.xml.amd64

bacula-client, better handling for remote director and messages pkg 1.0.11
submitted by compdoc

bacula-client, better handling for remote director and messages pkg 1.0.11

---

config/ntopng/ntopng.inc
config/ntopng/ntopng.xml
pkg_config.10.xml
pkg_config.8.xml
pkg_config.8.xml.amd64

ntopng.xml 
- Moved all PHP code to separate ntopng.inc
- Add a button to wipe ntopng data
- Add enable checkbox
- Add checkbox to either keep or delete settings and data on uninstall/reinstall.
- Some description cosmetics
ntopng.inc (added)
- Moved all PHP code here; hopefully should fix most of the whacky issues mentioned in Bug #4880
- Add wipe data feature
- Add minimum password length check
- Optionally wipe all traffic data, graphs and settings on uninstall if so configured

ntopng - reworked package

---

config/avahi/avahi.inc
config/avahi/avahi.xml
pkg_config.10.xml
pkg_config.8.xml
pkg_config.8.xml.amd64

avahi - expose many more config options in GUI

---

config/squid3/34/squid.inc
config/squid3/34/squid_antivirus.xml
config/squid3/34/squid_cache.xml
config/squid3/34/squid_monitor.php
config/squid3/34/squid_nac.xml
config/squid3/34/squid_traffic.xml
pkg_config.10.xml

Fix the stupid recursive chown bug, fix cache creation on install on boxes that never had Squid cache configured, fix uninstall, plus some cosmetics...
Done here for the moment; other things should wait for next round before this gets messy.

squid3 - bugfixes

---

config/spamd/spamd.inc
config/spamd/spamd.xml
config/spamd/spamd_settings.xml
pkg_config.10.xml
pkg_config.8.xml
pkg_config.8.xml.amd64

- fix insane pflogd logging - Bug #5231 (this package needs the pflogX interface, not pflogd daemon)
- fix blacklisting-only mode for spamd-setup
- fix rcfile
- add enable/disable feature to the package
- add input validation

spamd - multiple fixes

---

config/squid3/34/squid_antivirus.inc
pkg_config.10.xml

This is not being done on install for god knows what reason, despite the code being there. I have no time left to debug similar nonsense in package manager. Kindly merge this before the forums get flooded by more complaints.

Squid3 - fix clamav dirs handling

---

config/quagga_ospfd/quagga_ospfd.xml
pkg_config.10.xml
pkg_config.8.xml
pkg_config.8.xml.amd64

quagga_ospfd, set proper file download reference for quagga_ospfd_raw.xml

quagga_ospfd, set proper file download reference for quagga_ospfd_raw.xml

---

config/squid3/34/squid.inc
config/squid3/34/squid_antivirus.inc
config/squid3/34/squid_antivirus.xml
config/squid3/34/squid_antivirus_status.widget.php
config/squid3/34/squid_cache.xml
config/squid3/34/squid_monitor.php
config/squid3/34/squid_monitor_data.php
config/squid3/34/squid_nac.xml
config/squid3/34/squid_reverse.inc
config/squid3/34/squid_reverse_sync.xml
config/squid3/34/squid_sync.xml
config/squid3/34/squid_traffic.xml
config/squid3/34/squid_users.xml
pkg_config.10.xml

- Fixes issues reported by users on the forum now that things stabilized with 0.4.0, plus bunch of other unnoticed bugs.
- Also adds bunch of logs to the 'Real Time' tab
- Clean up the code in a couple of places.

Squid3 bugfixes - bonus round

---

config/squid3/34/squid_antivirus.inc
config/squid3/34/squid_reverse.inc
pkg_config.10.xml

Thanks you very much, PBI guys. Your product really "rocks". Shove a piece of barbed wire down there. 
(+ Fix some nonsense with Exchange 2013 reverse proxy while here.)

Squid3 - 	Fix clamav user account/group/dir permissions yet again

---

config/squid3/34/squid_antivirus_status.widget.php

Not really worth a version bump.

Squid3 - widget typo fix

---

config/lightsquid/lightsquid.inc
config/lightsquid/lightsquid.priv.inc
config/lightsquid/lightsquid.xml
config/lightsquid/sqstat.class.php
config/lightsquid/sqstat.css
config/lightsquid/sqstat.php
config/lightsquid/tpl/novopf/index.html
config/lightsquid/tpl/novopf/user_detail.html
config/lightsquid/tpl/novopf/user_month.html
config/lightsquid/tpl/novopf/whousesite.html
config/lightsquid/tpl/novosea/index.html
config/lightsquid/tpl/novosea/user_detail.html
config/lightsquid/tpl/novosea/user_month.html
config/lightsquid/tpl/novosea/whousesite.html
config/lightsquid/zhabascript.js
pkg_config.10.xml
pkg_config.8.xml
pkg_config.8.xml.amd64

- provide instructions to users and add corresponding input validation; completely stop touching Squid packages configuration directly
- fix cronjob handling
- fix 'Skip URL(s)' handling and add some basic validation to it as well
- fix lightsquid.cfg handling
- fix English and clean up the GUI
- fix file permissions
- add privileges configuration
- code style fixes
- HTML fixes
- ...

lightsquid package reworked

---

config/squid3/34/squid.inc

Another thing not really worth a version bump.

Accept "all" in 'Allowed Subnets' (Bug #4525)

---

config/zabbix2/zabbix2-agent.priv.inc
config/zabbix2/zabbix2-agent.xml
config/zabbix2/zabbix2-proxy.priv.inc
config/zabbix2/zabbix2-proxy.xml
config/zabbix2/zabbix2.inc
pkg_config.10.xml
pkg_config.8.xml
pkg_config.8.xml.amd64

Same stuff that's already been done for the zabbix LTS branch package versions. Also add privileges configuration to the packages.

zabbix2-agent/zabbix2-proxy - code style cleanup

---

config/suricata/suricata.inc
pkg_config.10.xml
pkg_config.8.xml
pkg_config.8.xml.amd64

- Fix CARP protocol/port selection
- Do some validations (IP/hostname, port, password) before attempting to sync
- Handle IPv6 addresses for sync target
- Code style cleanups while here
@bmeeks8 - Please, check this ;)

suricata - XMLRPC sync fixes

---

config/haproxy-devel/haproxy.priv.inc
config/haproxy-devel/haproxy.xml
config/haproxy-devel/pkg/haproxy.inc
config/haproxy-devel/pkg/haproxy_htmllist.inc
config/haproxy-devel/pkg/haproxy_upgrade_config.inc
config/haproxy-devel/pkg/haproxy_utils.inc
config/haproxy-devel/www/haproxy_files.php
config/haproxy-devel/www/haproxy_global.php
config/haproxy-devel/www/haproxy_listeners.php
config/haproxy-devel/www/haproxy_listeners_edit.php
config/haproxy-devel/www/haproxy_pool_edit.php
config/haproxy-devel/www/haproxy_pools.php
config/haproxy-devel/www/haproxy_stats.php
config/haproxy-devel/www/haproxy_templates.php
pkg_config.10.xml
pkg_config.8.xml
pkg_config.8.xml.amd64

haproxy-devel, pkg v0.32 allow usage of mailers/dns/'actions', rework of acl system.

haproxy-devel, pkg v0.32 allow usage of mailers/dns/'actions', rework of acl system.

---

config/squid3/34/squid.inc
config/squid3/34/squid_antivirus.inc

Doesn't work plus this is gone in 2.3 anyway.

squid3 - nuke update_output_window cruft

---

pkg_config.10.xml

haproxy-devel, change to 1.6.2 stable from ports

haproxy-devel, change to 1.6.2 stable from ports

---

config/squidGuard/squidguard.priv.inc
config/squidGuard/squidguard.xml
pkg_config.10.xml
pkg_config.8.xml
pkg_config.8.xml.amd64

Hey guys, kindly check that whatever thing that parses this swallows multiple &lt;conflicts&gt; tags per package. Couldn't find any code anywhere regarding this - at all.

Add privileges configuration to squidguard package

---

config/notes/notes.priv.inc
config/notes/notes.xml
pkg_config.10.xml
pkg_config.8.xml
pkg_config.8.xml.amd64

Improve some descriptions while here.

Add privileges configuration to notes package

---

config/routed/routed.inc
config/routed/routed.priv.inc
config/routed/routed.xml
pkg_config.10.xml
pkg_config.8.xml
pkg_config.8.xml.amd64

- Don't create rc script unless package is enabled
- When RIP is disabled in configuration, remove the rc script so that it does not get restarted on reboot
- Nuke /etc/gateways on uninstall

routed - add privileges configuration, improve service handling

---

config/mtr-nox11/mtr-nox11.priv.inc
config/mtr-nox11/mtr-nox11.xml
pkg_config.10.xml
pkg_config.8.xml
pkg_config.8.xml.amd64

Plus some cleanups while here.

Add privileges configuration to mtr-nox11 package

---

config/apache_mod_security/apache_mod_security.inc
config/apache_mod_security/apache_mod_security.priv.inc
config/apache_mod_security/apache_mod_security.xml
pkg_config.10.xml
pkg_config.8.xml
pkg_config.8.xml.amd64

- Disable mod_cgi since it's not packaged at all
- Add some PBI hacks

apache_mod_security - disable mod_cgi, add privileges configuration, PBI junk hacks

---

config/ladvd/ladvd.inc
config/ladvd/ladvd.priv.inc
config/ladvd/ladvd.xml
pkg_config.10.xml
pkg_config.8.xml
pkg_config.8.xml.amd64

- Improve service handling
- Improve some descriptions plus clean up while here.

Add privileges configuration to ladvd package

---

config/nmap/nmap.inc
config/nmap/nmap.priv.inc
config/nmap/nmap.xml
pkg_config.10.xml
pkg_config.8.xml
pkg_config.8.xml.amd64

Also	remove created symlink on uninstall, clean up input validations, improve descriptions, code style fixes.

Add privileges configuration to nmap package

---

config/nrpe2/nrpe2.inc
config/nrpe2/nrpe2.priv.inc
config/nrpe2/nrpe2.xml
pkg_config.10.xml
pkg_config.8.xml
pkg_config.8.xml.amd64

- Add input validations
- Fix package install/deinstall
- Fix disabling the service

nrpe2 package fixes

---

config/pfflowd/pfflowd.priv.inc
config/pfflowd/pfflowd.xml
pkg_config.10.xml
pkg_config.8.xml
pkg_config.8.xml.amd64

- Add Enable checkbox instead of using the foreach() hack
- Validate Source IP as well

pfflowd - add privileges configuration, fixes and cleanups

---

config/olsrd/olsrd.inc
config/olsrd/olsrd.priv.inc
config/olsrd/olsrd.xml
pkg_config.10.xml
pkg_config.8.xml
pkg_config.8.xml.amd64

- Fix service handling
- Fix plugin paths
- Disable the dynamic gateways options since the required plugin is missing in the package
- Add input validations
- Couple of other clenaups

olsrd package fixes, add privileges configuration

---

config/dansguardian/dansguardian.xml
config/dansguardian/dansguardian_rc.template
pkg_config.10.xml
pkg_config.8.xml
pkg_config.8.xml.amd64

Reported @ https://forum.pfsense.org/index.php?topic=75321.0

dansguardian - fix service (re)restart failure due to some lingering /tmp junk

---

config/bind/bind.priv.inc
config/bind/bind.xml
config/bind/bind_acls.xml
config/bind/bind_views.xml
config/bind/bind_zones.xml
config/shellcmd/shellcmd.xml
pkg_config.10.xml
pkg_config.8.xml
pkg_config.8.xml.amd64

Eh, did not intend to commit the shellcmd stuff here, but it does not matter really.

bind - add privileges configuration; shellcmd - nuke useless GUI tab

---

config/quagga_ospfd/quagga_ospfd.inc
config/quagga_ospfd/quagga_ospfd.priv.inc
config/quagga_ospfd/quagga_ospfd.xml
pkg_config.10.xml
pkg_config.8.xml
pkg_config.8.xml.amd64

- Add missing includes
- Fix var declarations
- Use full paths to binaries
- Code style

quagga_ospfd - add privileges configuration, some fixes

---

config/pfblockerng/pfblockerng.inc
config/pfblockerng/pfblockerng.php
pkg_config.10.xml

@BBcan177 - there's something obviously fishy with the entire pfb_global() thing, you might want to re-check the whole thing.

pfblockerng - fix check so that Alexa list is not downloaded when disabled

---

config/haproxy-devel/haproxy.xml
config/haproxy-devel/pkg/haproxy.inc
config/haproxy-devel/pkg/haproxy_socketinfo.inc
config/haproxy-devel/www/haproxy_global.php
config/haproxy-devel/www/haproxy_listeners_edit.php
config/haproxy-devel/www/haproxy_pool_edit.php
pkg_config.10.xml
pkg_config.8.xml
pkg_config.8.xml.amd64

haproxy-devel, small fixes pkg v0.35

haproxy-devel, small fixes pkg v0.35

---

config/haproxy-devel/haproxy.xml
config/haproxy-devel/pkg/haproxy.inc
config/haproxy-devel/pkg/haproxy_gui.inc
config/haproxy-devel/pkg/haproxy_htmllist.inc
config/haproxy-devel/www/haproxy_listeners.php
config/haproxy-devel/www/haproxy_listeners_edit.php
config/haproxy-devel/www/haproxy_pools.php
config/haproxy-devel/www/widgets/widgets/haproxy.widget.php
pkg_config.10.xml
pkg_config.8.xml
pkg_config.8.xml.amd64

haproxy-devel, small fixes for showing/hiding acl fields not applicable, fix custom action, pkg v0.36

haproxy-devel, small fixes for showing/hiding acl fields, fix custom action, pkg v0.36

---

config/pfblockerng/pfblockerng.inc
pkg_config.10.xml

* Bug fix for missing variable
* Mod to file verification process

pfBlockerNG - version 2.0.6
